force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>DHS_Contact_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/DHS_Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Contact__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investigator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/DHS_Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Lead__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Subject Interview</fullName>
            </value>
            <value>
                <fullName>General Record</fullName>
            </value>
            <value>
                <fullName>Subject Recontact</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipName>DHS_Case_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipName>DHS_Contact_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Item_number__c.field-meta.xml
<CustomField>
    <fullName>Item_number__c</fullName>
    <label>Item number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject Recontact (SUBC)</fullName>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Publicly Available Electronic Information (PAEI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DHSOrderROIReportControllerV2Test.cls
@isTest
/** Exercises the existing DHSOrderROIReportControllerV2 behavior. */
@SuppressWarnings('PMD.AnnotationsNamingConventions, PMD.ApexUnitTestClassShouldHaveRunAs, PMD.NcssCount')
public class DHSOrderROIReportControllerV2Test {
    
    @IsTest static void testFullCoverage() {
        User pmoUser = PPFDHSTestUserFactory.createPmoUser();
        System.runAs(pmoUser) {
        // Setup test data
        DHS_Contact__c testContact = new DHS_Contact__c(
            First_Name__c = 'Test',
            Last_Name__c = 'Contact',
            Email__c= 'test@example.com',
            Address__c = '123 Street',
            City__c = 'Testville',
            State__c = 'TS',
            Zip__c = '12345',
            SSN__c = '123-45-6789',
            Contact_Type__c = 'Subject'
        );
        insert testContact;

        DHS_Case__c testCase = new DHS_Case__c(
            DHS_Contact__c = testContact.Id,
            Subject_Type__c = 'Applicant',
            DHS_Assigned_To__c = UserInfo.getUserId()
        );
        insert testCase;

        // Leads
        List<DHS_Lead__c> leads = new List<DHS_Lead__c>();
        for (Integer i = 1; i <= 3; i++) {
            leads.add(new DHS_Lead__c(
                DHS_Case__c = testCase.Id,
                LeadType__c = 'Residence (RESI)',
                Coverage_Type__c = (i / 2 != 1) ? 'Personal' : 'Other',
                Item_number__c = i
            ));
        }
        leads.add(new DHS_Lead__c( // No-subheader type
            DHS_Case__c = testCase.Id,
            LeadType__c = 'Subject Interview (ESI/TESI)',
            Coverage_Type__c = 'Other',
            Item_number__c = 4
        ));
        insert leads;

        // Simulate ApexPages parameters
        Test.setCurrentPageReference(new PageReference('/apex/DHSOrderROIReportV2')); // Replace with actual page
        ApexPages.currentPage().getParameters().put('id', testCase.Id);
        ApexPages.currentPage().getParameters().put('type', 'TestType');

        Test.startTest();
        DHSOrderROIReportControllerV2 controller = new DHSOrderROIReportControllerV2();

        // Simulate lead numbers/subheaders for report generation
        Integer leadNum = 1;
        for (DHSOrderROIReportControllerV2.AllLeads ld : controller.leadRecordss) {
            if (!ld.issubheader) {
                ld.leadNumber = leadNum++;
            } else {
                ld.subheaderNumber = '1';
            }
        }
        controller.updateLeads();
        controller.reloadLeads();
        leadNum = 1;
        for (DHSOrderROIReportControllerV2.AllLeads leadWrapper :
            controller.leadRecordss) {
            if (!leadWrapper.issubheader) {
                leadWrapper.leadNumber = leadNum++;
            } else {
                leadWrapper.subheaderNumber = '1';
            }
        }
        controller.leadRecordss[0].headerTitle = true;
        controller.leadRecords = new List<DHSOrderROIReportControllerV2.LeadRecord>{
            new DHSOrderROIReportControllerV2.LeadRecord(leads[0], 1),
            new DHSOrderROIReportControllerV2.LeadRecord(leads[1], 2)
        };

        PageReference result1 = controller.GenerateROIReport();
        System.assertNotEquals(null, result1, 'Assertion failed in DHSOrderROIReportControllerV2Test at source line 83');

        PageReference result2 = controller.GenerateNattachROIReport();
        System.assertNotEquals(null, result2, 'Assertion failed in DHSOrderROIReportControllerV2Test at source line 86');

        controller.currentsequenceid = null;
        controller.GenerateROIDraft();
        controller.GenerateROIDraft();
        System.assertNotEquals(null, controller.PreviewUsingDhsDesigner(), 'Assertion failed in DHSOrderROIReportControllerV2Test at source line 91');
        System.assertNotEquals(null, controller.backToReport(), 'Assertion failed in DHSOrderROIReportControllerV2Test at source line 92');

        ApexPages.currentPage().getParameters().put(
            'sequenceid', controller.currentsequenceid
        );
        DHSOrderROIReportControllerV2 previewController =
            new DHSOrderROIReportControllerV2();
        System.assertEquals(true, previewController.showPreview, 'Assertion failed in DHSOrderROIReportControllerV2Test at source line 99');

        // Call future method directly
        Test.stopTest();
        System.assertNotEquals(null, controller.leadRecordss, 'Assertion failed in DHSOrderROIReportControllerV2Test at source line 103');
        }
    }
}