force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/costpoint_code__c.field-meta.xml
<CustomField>
    <fullName>costpoint_code__c</fullName>
    <label>costpoint code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>DHS_Contact_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Delivered canceled</fullName>
            </value>
            <value>
                <fullName>Delivered pending item(s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/DHS_Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investigator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Invoice__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>DHS_Case__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Invoice__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <formula>TEXT(DHS_Case__r.Case_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Invoice__c/fields/Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Completed_Date__c</fullName>
    <formula>DHS_Lead__r.Completed_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHS_Invoice__c/fields/Costpoint_Code__c.field-meta.xml
<CustomField>
    <fullName>Costpoint_Code__c</fullName>
    <formula>DHS_Case__r.costpoint_code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Costpoint Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Invoice__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>DHS_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Invoice__c/fields/DHS_Lead__c.field-meta.xml
<CustomField>
    <fullName>DHS_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>DHS_Lead__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>DHS_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Invoice__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <formula>DHS_Lead__r.Item_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHS_Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>In-Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/DHS_Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Lead__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Subject Interview</fullName>
            </value>
            <value>
                <fullName>General Record</fullName>
            </value>
            <value>
                <fullName>Subject Recontact</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipName>DHS_Case_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipName>DHS_Contact_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Item_number__c.field-meta.xml
<CustomField>
    <fullName>Item_number__c</fullName>
    <label>Item number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject Recontact (SUBC)</fullName>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Publicly Available Electronic Information (PAEI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Personal_Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Personal_Contact_Method__c</fullName>
    <label>Personal Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>By Telephone/Fax</fullName>
                <isActive>false</isActive>
                <label>By Telephone/Fax</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Assigned Not Accepted</fullName>
            </value>
            <value>
                <fullName>Investigator Rejected</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Applied For Waiver</fullName>
            </value>
            <value>
                <fullName>QA Rejected</fullName>
            </value>
            <value>
                <fullName>QA Review Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>QA Rejection Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Was_Subject_Interview_Conducted__c.field-meta.xml
<CustomField>
    <fullName>Was_Subject_Interview_Conducted__c</fullName>
    <label>Was Subject interview conducted</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Was_the_record_obtained_Personal__c.field-meta.xml
<CustomField>
    <fullName>Was_the_record_obtained_Personal__c</fullName>
    <label>Was the record obtained Personal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes, Source was interviewed</fullName>
            </value>
            <value>
                <fullName>No, Unable to interview source</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DHSInvoiceModuleControllerTest.cls
@IsTest
@SuppressWarnings('PMD.ApexAssertionsShouldIncludeMessage')
private class DHSInvoiceModuleControllerTest {
    @IsTest
    static void fetchInvoiceRecordsUsesCompletedLeadsAndPaychexId() {
        User pmoUser = createUser('pmo', 'PMO', 'Employee');

        System.runAs(pmoUser) {
            insert new Account(Name = System.Label.DHS_AccountName);

            DHS_Contact__c subject = new DHS_Contact__c(
                First_Name__c = 'Subject',
                Last_Name__c = 'Smith',
                Email__c = 'subject@example.com',
                Contact_Type__c = 'Subject',
                SSN__c = '123-45-6789'
            );
            insert subject;

            DHS_Case__c caseRecord = new DHS_Case__c(
                DHS_Contact__c = subject.Id,
                DHS_Assigned_To__c = pmoUser.Id,
                Case_Number__c = 'TEST1234',
                Case_Type__c = 'Tier 5',
                Service_Days__c = '40',
                Status__c = 'Active'
            );
            caseRecord.put('Costpoint_Code__c', '3207.C01.0008.T1');
            insert caseRecord;

            DHS_Lead__c completedLead = new DHS_Lead__c(
                DHS_Case__c = caseRecord.Id,
                DHS_Assigned_To__c = pmoUser.Id,
                DHS_Contact__c = subject.Id,
                LeadType__c = 'Subject Interview (ESI/TESI)',
                Coverage_Type__c = 'Subject Interview',
                Item_number__c = 3,
                Was_Subject_Interview_Conducted__c = 'Yes',
                Completed_Date__c = Date.today()
            );
            insert completedLead;
            completedLead.Status__c = 'Completed';
            update completedLead;

            DHS_Lead__c rejectedLead = new DHS_Lead__c(
                DHS_Case__c = caseRecord.Id,
                DHS_Assigned_To__c = pmoUser.Id,
                DHS_Contact__c = subject.Id,
                LeadType__c = 'General (GENL)',
                Coverage_Type__c = 'Personal',
                Item_number__c = 6,
                Was_the_record_obtained_Personal__c = 'Yes, Source was interviewed',
                Personal_Contact_Method__c = 'Telephone',
                Completed_Date__c = Date.today()
            );
            insert rejectedLead;

            rejectedLead.Status__c = 'QA Rejected';
            rejectedLead.Completed_Date__c = Date.today();
            update rejectedLead;

            DHSInvoiceModuleController controller = new DHSInvoiceModuleController();

            controller.periodStartDate = Date.today().addDays(-1);
            controller.periodEndDate = Date.today();
            controller.selectedUserOption = 'Employee';
            controller.selectedWorkerId = pmoUser.Id;

            Test.startTest();
            controller.FetchInvoiceRecords();
            Test.stopTest();

            System.assertEquals(1, controller.invoices.size(), 'Only completed, non-QA-rejected leads should be returned.');
            System.assertEquals(1, controller.pageNumber);
            System.assertEquals(1, controller.totalPages);
            System.assertEquals(1, controller.totalRecordCount);
            System.assertEquals(true, controller.disablePrev);
            System.assertEquals(true, controller.disableNext);
            DHS_Invoice__c row = controller.invoices[0];
            System.assertNotEquals(null, row.Id);
        }
    }

    private static User createUser(String aliasPrefix, String userType, String candidateType) {
        Profile profileRecord = [
            SELECT Id
            FROM Profile
            WHERE Name = 'Standard User'
            LIMIT 1
        ];
        String uniqueValue = String.valueOf(DateTime.now().getTime());
        User testUser = new User(
            Alias = aliasPrefix.left(8),
            Email = aliasPrefix + uniqueValue + '@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = aliasPrefix,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = profileRecord.Id,
            TimeZoneSidKey = 'America/New_York',
            UserName = aliasPrefix + uniqueValue + '@example.com',
            User_Type__c = userType,
            Candidate_type__c = candidateType,
            System_Access__c = 'Intel'
        );
        insert testUser;
        insert new PermissionSetAssignment(
            AssigneeId = testUser.Id,
            PermissionSetId = [
                SELECT Id FROM PermissionSet
                WHERE Name = 'DHS_Package_System_Admin_Access'
                LIMIT 1
            ].Id
        );
        return testUser;
    }
    @IsTest
static void initializesControllerOptionsAndCycleDates() {
    User pmoUser = createUser(
        'pmoInit',
        'PMO',
        'Employee'
    );

    System.runAs(pmoUser) {
        Test.startTest();
        DHSInvoiceModuleController controller =
            new DHSInvoiceModuleController();
        Test.stopTest();

        System.assertEquals(true, controller.isPMOUser);
        System.assertEquals('DHS_All', controller.selectedUserOption);
        System.assertEquals('DHS_All', controller.selectedWorkerId);

        System.assertEquals(1, controller.pageNumber);
        System.assertEquals(1, controller.totalPages);
        System.assertEquals(0, controller.totalRecordCount);
        System.assertEquals(0, controller.currentRecordCount);
        System.assertEquals(true, controller.disablePrev);
        System.assertEquals(true, controller.disableNext);

        System.assertEquals(4, controller.userTypeOptions.size());
        System.assertEquals(
            'DHS_All',
            controller.userTypeOptions[0].getValue()
        );
        System.assertEquals(
            'Employee',
            controller.userTypeOptions[1].getValue()
        );
        System.assertEquals(
            'SCA',
            controller.userTypeOptions[2].getValue()
        );
        System.assertEquals(
            'Non-SCA',
            controller.userTypeOptions[3].getValue()
        );

        System.assertNotEquals(null, controller.workerOptions);
        System.assertEquals(
            'DHS_All',
            controller.workerOptions[0].getValue()
        );

        System.assertNotEquals(null, controller.cycleDates);
        System.assertNotEquals(null, controller.cycleDateOptions);
        System.assert(
            !controller.cycleDateOptions.isEmpty()
        );
        System.assertEquals(
            '',
            controller.cycleDateOptions[0].getValue()
        );
        System.assertEquals(
            'All',
            controller.cycleDateOptions[0].getLabel()
        );
    }
}

@IsTest
static void refreshesWorkerOptionsByCandidateType() {
    User pmoUser = createUser(
        'pmoRefresh',
        'PMO',
        'Employee'
    );

    System.runAs(pmoUser) {
        DHSInvoiceModuleController controller =
            new DHSInvoiceModuleController();

        controller.selectedUserOption = 'Employee';
        controller.selectedWorkerId = pmoUser.Id;

        Test.startTest();
        controller.RefreshWorkerOptions();
        Test.stopTest();

        System.assertEquals(
            'DHS_All',
            controller.selectedWorkerId
        );
        System.assertNotEquals(null, controller.workerOptions);
        System.assert(
            !controller.workerOptions.isEmpty()
        );
        System.assertEquals(
            'DHS_All',
            controller.workerOptions[0].getValue()
        );
    }
}

@IsTest
static void refreshesAllWorkerOptions() {
    User pmoUser = createUser(
        'pmoAll',
        'PMO',
        'Employee'
    );

    System.runAs(pmoUser) {
        DHSInvoiceModuleController controller =
            new DHSInvoiceModuleController();

        controller.selectedUserOption = 'DHS_All';
        controller.selectedWorkerId = pmoUser.Id;

        Test.startTest();
        controller.RefreshWorkerOptions();
        Test.stopTest();

        System.assertEquals(
            'DHS_All',
            controller.selectedWorkerId
        );
        System.assertNotEquals(null, controller.workerOptions);
        System.assert(
            !controller.workerOptions.isEmpty()
        );
    }
}

@IsTest
static void nonPMOUserCannotFetchInvoices() {
    User investigator = createUser(
        'invFetch',
        'INV',
        'Employee'
    );

    System.runAs(investigator) {
        DHSInvoiceModuleController controller =
            new DHSInvoiceModuleController();

        System.assertEquals(false, controller.isPMOUser);

        /*
         * Set values first to verify FetchInvoiceRecords resets
         * the pagination state before returning.
         */
        controller.pageNumber = 10;
        controller.totalPages = 10;
        controller.totalRecordCount = 100;
        controller.currentRecordCount = 50;
        controller.disablePrev = false;
        controller.disableNext = false;

        Test.startTest();
        controller.FetchInvoiceRecords();
        Test.stopTest();

        System.assertNotEquals(null, controller.invoices);
        System.assertEquals(0, controller.invoices.size());
        System.assertEquals(1, controller.pageNumber);
        System.assertEquals(1, controller.totalPages);
        System.assertEquals(0, controller.totalRecordCount);
        System.assertEquals(0, controller.currentRecordCount);
        System.assertEquals(true, controller.disablePrev);
        System.assertEquals(true, controller.disableNext);
    }
}

@IsTest
static void fetchesUsingCycleDateFilter() {
    User pmoUser = createUser(
        'pmoCycle',
        'PMO',
        'Employee'
    );

    System.runAs(pmoUser) {
        DHSInvoiceModuleController controller =
            new DHSInvoiceModuleController();

        controller.selectedCycleFilterDate =
            String.valueOf(Date.today().addDays(-14));
        controller.selectedUserOption = 'DHS_All';
        controller.selectedWorkerId = 'DHS_All';

        Test.startTest();
        controller.FetchInvoiceRecords();
        Test.stopTest();

        System.assertEquals(
            Date.today().addDays(-14),
            controller.cycleFilterDate
        );
        System.assertNotEquals(
            null,
            DHSInvoiceModuleController.criteria
        );
        System.assertNotEquals(
            null,
            controller.queryForNextRecords
        );
        System.assertEquals(1, controller.pageNumber);
        System.assert(
            controller.totalPages >= 1
        );
    }
}

@IsTest
static void fetchesUsingUserAndWorkerFilters() {
    User pmoUser = createUser(
        'pmoFilter',
        'PMO',
        'Employee'
    );

    System.runAs(pmoUser) {
        DHSInvoiceModuleController controller =
            new DHSInvoiceModuleController();

        controller.selectedCycleFilterDate = null;
        controller.selectedUserOption = 'Employee';
        controller.selectedWorkerId = pmoUser.Id;

        Test.startTest();
        controller.FetchInvoiceRecords();
        Test.stopTest();

        System.assertEquals(null, controller.cycleFilterDate);
        System.assertNotEquals(
            null,
            DHSInvoiceModuleController.criteria
        );
        System.assertNotEquals(
            null,
            controller.queryForNextRecords
        );

        String serializedCriteria =
            String.valueOf(
                DHSInvoiceModuleController.criteria
            );

        System.assert(
            serializedCriteria.contains('Candidate_type__c')
        );
        System.assert(
            serializedCriteria.contains(pmoUser.Id)
        );
    }
}

@IsTest
static void paginationMethodsHandleInvalidState() {
    User pmoUser = createUser(
        'pmoPage',
        'PMO',
        'Employee'
    );

    System.runAs(pmoUser) {
        DHSInvoiceModuleController controller =
            new DHSInvoiceModuleController();

        System.assertEquals(null, controller.queryForNextRecords);
        System.assertEquals(null, controller.firstRecordName);
        System.assertEquals(null, controller.lastRecordName);
        System.assertEquals(1, controller.pageNumber);

        Test.startTest();
        controller.handlePrev();
        controller.handleNext();
        Test.stopTest();

        System.assertEquals(1, controller.pageNumber);
        System.assertEquals(true, controller.disablePrev);
        System.assertEquals(true, controller.disableNext);
    }
}

@IsTest
static void rebuildsCycleDateOptions() {
    User pmoUser = createUser(
        'pmoDates',
        'PMO',
        'Employee'
    );

    System.runAs(pmoUser) {
        DHSInvoiceModuleController controller =
            new DHSInvoiceModuleController();

        controller.cycleDates.clear();
        controller.cycleDateOptions.clear();

        Test.startTest();
        controller.getAllCycleDates();
        Test.stopTest();

        System.assert(
            !controller.cycleDates.isEmpty()
        );
        System.assertEquals(
            controller.cycleDates.size() + 1,
            controller.cycleDateOptions.size()
        );

        Date newestCycleDate = controller.cycleDates[
            controller.cycleDates.size() - 1
        ];

        System.assertEquals(
            String.valueOf(newestCycleDate),
            controller.cycleDateOptions[1].getValue()
        );

        String expectedLabel =
            String.valueOf(newestCycleDate.month()).leftPad(2, '0') +
            '/' +
            String.valueOf(newestCycleDate.day()).leftPad(2, '0') +
            '/' +
            String.valueOf(newestCycleDate.year());

        System.assertEquals(
            expectedLabel,
            controller.cycleDateOptions[1].getLabel()
        );
    }
}

}