force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/Assigned_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Name__c</fullName>
    <formula>DHS_Assigned_To__r.FirstName  +&apos; &apos; +DHS_Assigned_To__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Delivered canceled</fullName>
            </value>
            <value>
                <fullName>Delivered pending item(s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Document_Request__c/DHS_Document_Request__c.object-meta.xml
<CustomObject>
    <label>Document Request</label>
    <nameField>
        <displayFormat>DR-{0000000}</displayFormat>
        <label>Document Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Document_Request__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DHS Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipLabel>DHS Document Requests</relationshipLabel>
    <relationshipName>DHS_Case_Document_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Document_Request__c/fields/DHS_Lead__c.field-meta.xml
<CustomField>
    <fullName>DHS_Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>DHS_Lead__c</referenceTo>
    <relationshipLabel>Document Requests</relationshipLabel>
    <relationshipName>DHS_Document_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHS_Document_Request__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DHS_Document_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documents Requested</fullName>
            </value>
            <value>
                <fullName>Documents Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Document_Request__c/fields/Subject_Comments__c.field-meta.xml
<CustomField>
    <fullName>Subject_Comments__c</fullName>
    <label>Subject Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/DHS_Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Lead__c/fields/Assigned_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Name__c</fullName>
    <formula>DHS_Assigned_To__r.FirstName + &apos; &apos; + DHS_Assigned_To__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipName>DHS_Case_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Assigned Not Accepted</fullName>
            </value>
            <value>
                <fullName>Investigator Rejected</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Applied For Waiver</fullName>
            </value>
            <value>
                <fullName>QA Rejected</fullName>
            </value>
            <value>
                <fullName>QA Review Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>QA Rejection Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DHSSubjectDocumentsUploadController.cls
/** Controls subject-facing DHS document-request uploads. */
@SuppressWarnings('PMD.ApexCRUDViolation, PMD.ApexDoc, PMD.ApexXSSFromURLParam, PMD.AvoidBooleanMethodParameters, PMD.MethodNamingConventions')
public without sharing class DHSSubjectDocumentsUploadController{
    public string documentRequestId {get;set;}
    public DHS_Document_Request__c documentRequest {get;set;}
    public boolean showUploadPanel {get;set;}
    public boolean showAfterUploadPanel {get;set;}
    public boolean showExpiryPanel {get;set;}
    public list<attachment> attachmentsList {get;set;}
    
    public DHSSubjectDocumentsUploadController(){
        documentRequestId = apexpages.currentpage().getparameters().get('id');
        documentRequestId = String.valueOf(Id.valueOf(decodeURLParams(documentRequestId)));
        
        FetchDocumentRequest();
    }
    
    public void FetchDocumentRequest(){
        showUploadPanel = false;
        showAfterUploadPanel = false;
        showExpiryPanel = false;
        documentRequest = [Select Id, DHS_Lead__c, DHS_Lead__r.Assigned_To_Name__c,DHS_Lead__r.DHS_Case__r.Case_Number__c, Expiration_Date__c, CreatedDate, Status__c, Subject_Comments__c, Request_Expired__c from DHS_Document_Request__c WHERE ID=: documentRequestId];
        if(documentRequest.Status__c == 'Documents Requested' && !documentRequest.Request_Expired__c){
            showUploadPanel = true;    
        }
        if(documentRequest.Status__c == 'Documents Received' && !documentRequest.Request_Expired__c){
            showAfterUploadPanel = true;    
        }
        if(documentRequest.Request_Expired__c){
            showExpiryPanel = true;    
        }
        attachmentsList = new list<attachment>();
        attachmentsList = [Select Id, parentId, Name, CreatedDate, Description from Attachment where parentId =:documentRequestId];
    
    }
    
    public void submitaction(){
        documentRequest.Status__c='Documents Received';
        update documentRequest;
        FetchDocumentRequest();
    }
    public string deleteAttachmentId{get;set;}
    public void DeleteAttachment(){
        delete [select Id from Attachment where id=:deleteAttachmentId];
        FetchDocumentRequest();
    }
    
    public void autosaveaction(){
        update documentRequest;
    }
    
    private String decodeURLParams(String encodedString){
         // take the base64 encoded parameter and create base64 decoded Blob from it   
         Blob afterblob = EncodingUtil.base64Decode(encodedString);
         // Convert the blob back to a string and print it in the debug log
         return afterblob.toString();
        
    }

}