force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>DHS_Contact_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/DHS_Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investigator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Document__c/DHS_Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Document__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>DHS_Case_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DHSForesiteFileUploadPageControllerTest.cls
@IsTest
/** Exercises the existing DHSForesiteFileUploadPageController behavior. */
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
private class DHSForesiteFileUploadPageControllerTest {
    @IsTest
    static void savesAttachmentForCase() {
        User pmoUser = PPFDHSTestUserFactory.createPmoUser();
        System.runAs(pmoUser) {
        DHS_Contact__c subject = new DHS_Contact__c(
            First_Name__c = 'DHS',
            Last_Name__c = 'File Test',
            SSN__c = '123-45-6789', Contact_Type__c = 'Subject'
        );
        insert subject;
        DHS_Case__c caseRecord = new DHS_Case__c(
            Case_Number__c = 'UPLOAD-TEST',
            DHS_Contact__c = subject.Id,
            Subject_Type__c = 'Applicant',
            DHS_Assigned_To__c = UserInfo.getUserId()
        );
        insert caseRecord;
        Test.setCurrentPage(Page.DHSMultifileuploadPage);
        ApexPages.currentPage().getParameters().put('caseid', caseRecord.Id);
        Attachment upload = new Attachment(
            Body = Blob.valueOf('test'),
            Name = 'foresite-upload.txt'
        );

        DHSForesiteFileUploadPageController controller =
            new DHSForesiteFileUploadPageController(
                new ApexPages.StandardController(upload)
            );
        PageReference result = controller.saveAndRedirect();

        System.assertNotEquals(null, result, 'Assertion failed in DHSForesiteFileUploadPageControllerTest at source line 35');
        System.assert(result.getUrl().contains(String.valueOf(caseRecord.Id)), 'Assertion failed in DHSForesiteFileUploadPageControllerTest at source line 36');
        DHS_Document__c document = [
            SELECT Id
            FROM DHS_Document__c
            WHERE DHS_Case__c = :caseRecord.Id
            LIMIT 1
        ];
        System.assertEquals(1, [
            SELECT COUNT()
            FROM Attachment
            WHERE ParentId = :document.Id
        ], 'Assertion failed in DHSForesiteFileUploadPageControllerTest at source line 43');
        }
    }
}