force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DHSROIReportControllerV2Test.cls
@IsTest
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs,PMD.ApexAssertionsShouldIncludeMessage')
private class DHSROIReportControllerV2Test {
    @IsTest
    static void buildsVersionTwoReportWithoutLeads() {
        DHS_Case__c parentCase = new DHS_Case__c(Case_Number__c = 'ROI-V2-TEST');
        insert parentCase;
        Test.setCurrentPage(Page.DHSROIReport);
        ApexPages.currentPage().getParameters().put('id', parentCase.Id);
        DHSROIReportControllerV2 controller = new DHSROIReportControllerV2();
        System.assertEquals(parentCase.Id, controller.caseRecord.Id);
        System.assertEquals(0, controller.totalLeads);
    }
}