force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Message__c/DHS_Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <displayFormat>Message-{000000}</displayFormat>
        <label>Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Message__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>DHS_Case_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Message__c/fields/DHS_From_User__c.field-meta.xml
<CustomField>
    <fullName>DHS_From_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_From_User_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Message__c/fields/DHS_To_User__c.field-meta.xml
<CustomField>
    <fullName>DHS_To_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Messages1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Message__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Message__c/fields/Read__c.field-meta.xml
<CustomField>
    <fullName>Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DHSMyMessagesControllerTest.cls
@IsTest
/** Exercises the existing DHSMyMessagesController behavior. */
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveAsserts')
private class DHSMyMessagesControllerTest {
    @TestSetup
    static void setupUser() {
        PPFDHSTestUserFactory.createPmoUser();
    }

    @IsTest
    static void loadsAndRefreshesCurrentMessage() {
        System.runAs(PPFDHSTestUserFactory.getPmoUser()) {
            DHS_Case__c parentCase = new DHS_Case__c(Case_Number__c = 'MESSAGE-TEST');
            insert parentCase;
            DHS_Message__c message = new DHS_Message__c(
                DHS_Case__c = parentCase.Id,
                Message_Body__c = 'Body',
                Subject__c = 'Subject',
                DHS_From_User__c = UserInfo.getUserId(),
                DHS_To_User__c = UserInfo.getUserId(),
                Read__c = false,
                UnRead__c = true
            );
            insert message;
            DHSMyMessagesController controller = new DHSMyMessagesController();
            controller.currentMessageId = message.Id;
            controller.FetchCurrentMessageAction();
            controller.RefreshAction();
            System.assertEquals(message.Id, controller.currentMessage.Id, 'Assertion failed in DHSMyMessagesControllerTest at source line 29');
        }
    }

    @IsTest
    static void sendsMessagesToEachRecipientGroup() {
        System.runAs(PPFDHSTestUserFactory.getPmoUser()) {
            DHSMyMessagesController controller = new DHSMyMessagesController();
            controller.messageBody = 'Coverage message';
            controller.messageSubject = 'Coverage subject';

            for (String recipientGroup : new List<String>{
                'All Program Members',
                'All Investigators',
                'All PMOs',
                'All CMOs',
                'All QAs'
            }) {
                controller.selecteToAddressOption = recipientGroup;
                controller.SendMessage();
                controller.messageBody = 'Coverage message';
                controller.messageSubject = 'Coverage subject';
            }
        }
    }
}