force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Document__c/DHS_Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Document__c/fields/Added_By__c.field-meta.xml
<CustomField>
    <fullName>Added_By__c</fullName>
    <label>Added By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Document__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>DHS_Case_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DHSUploadMultiFileUpload.cls
/** Retains the existing DHSUploadMultiFileUpload integration and application behavior. */
@SuppressWarnings('PMD.ApexSharingViolations, PMD.ApexDoc, PMD.DebugsShouldUseLoggingLevel, PMD.AvoidHardcodingId, PMD.ApexXSSFromURLParam, PMD.ApexCRUDViolation')
public class DHSUploadMultiFileUpload {
    public string caseId {get;set;}
    public string recordId {get;set;}
    public DHSUploadMultiFileUpload(){
        caseId = apexpages.currentpage().getparameters().get('caseid');
        recordId = 'a02cn000000xbhtAAA';
    }
        
    @RemoteAction
    public static String processUploadedFiles(string caseId,string fileName) {
		DHS_Document__c doc = New DHS_Document__c();
		doc.Added_By__c = [Select Id,Name from user where id=:userinfo.getuserid()].Name;
		doc.DHS_Case__c = caseId;
		doc.Name__c = fileName;
        insert doc;
        return doc.Id;
    }
}