force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>DHS_Contact_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/DHS_Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investigator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DHSUploadMultiFileUploadTest.cls
@IsTest
/** Exercises the DHS multi-file upload entry points. */
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
private class DHSUploadMultiFileUploadTest {
    @IsTest
    static void uploads() {
        User pmoUser = PPFDHSTestUserFactory.createPmoUser();
        System.runAs(pmoUser) {
            DHS_Contact__c contactRecord = new DHS_Contact__c(
                First_Name__c = 'Test', Last_Name__c = 'Subject',
                Email__c = 'upload@test.com', Contact_Type__c = 'Subject',
                SSN__c = '123-45-6789'
            );
            insert contactRecord;
            DHS_Case__c caseRecord = new DHS_Case__c(
                DHS_Contact__c = contactRecord.Id,
                DHS_Assigned_To__c = UserInfo.getUserId()
            );
            insert caseRecord;
            Test.setCurrentPage(new PageReference('/apex/upload'));
            ApexPages.currentPage().getParameters().put(
                'caseid', caseRecord.Id
            );
            System.assertEquals(
                caseRecord.Id,
                new DHSUploadMultiFileUpload().caseId
            , 'Assertion failed in DHSUploadMultiFileUploadTest at source line 24');
            String documentId = DHSUploadMultiFileUpload.processUploadedFiles(
                caseRecord.Id, 'file.pdf'
            );
            System.assertNotEquals(null, documentId, 'Assertion failed in DHSUploadMultiFileUploadTest at source line 31');
        }
    }
}