force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>DHS_Contact_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/DHS_Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investigator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/DHS_Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipName>DHS_Case_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipName>DHS_Contact_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DHSSubjFileUploadAuthPageCtrlTest.cls
@IsTest
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
public class DHSSubjFileUploadAuthPageCtrlTest {
	  @IsTest private static void testMethod1(){
     	 DHS_Contact__c con = new DHS_Contact__c();
         con.First_Name__c = 'Test';
         con.Last_Name__c = 'Name';
         con.Email__c  = 'test@test.com';
         con.Contact_Type__c = 'Subject';
		 con.SSN__c = '123-12-1123';
         insert con;
         DHS_Case__c diaCase = new DHS_Case__c();
         diaCase.DHS_Contact__c = con.id;
         diaCase.DHS_Assigned_To__c = userinfo.getuserId();
         insert diaCase;
        
        PageReference dHSSubjectFileUploadAuthPage = Page.dHSSubjectFileUploadAuthPage;
        Test.setCurrentPage(dHSSubjectFileUploadAuthPage);
        dHSSubjectFileUploadAuthPage.getParameters().put('id',diaCase.id); 
        DHSSubjectFileUploadAuthPageController ctrl =new DHSSubjectFileUploadAuthPageController();
        ctrl.ssnUserInput = '0000';
        pagereference pref = ctrl.AuthMethod(); System.assertNotEquals(null, pref, 'Expected pref to be initialized');
        System.assertEquals(false, ctrl.isAuthenticatedSuccess, 'Expected the asserted condition to hold');

        ctrl.ssnUserInput = '1123';
        try {
            ctrl.AuthMethod();
            System.assert(false, 'Expected required lead validation');
        } catch (DmlException expected) {
            System.assert(expected.getMessage().contains('DHS_Lead__c'), 'Expected assertion condition to hold');
        }
        System.assertEquals(true, ctrl.isAuthenticatedSuccess, 'Expected the asserted condition to hold');
      }
}