force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/Assigned_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Name__c</fullName>
    <formula>DHS_Assigned_To__r.FirstName  +&apos; &apos; +DHS_Assigned_To__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/Assignee_Date__c.field-meta.xml
<CustomField>
    <fullName>Assignee_Date__c</fullName>
    <label>Assignee Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>DHS_Contact_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/Investigations_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Investigations_Review_Date__c</fullName>
    <label>Investigations Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/QA_and_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>QA_and_Review_Date__c</fullName>
    <label>QA and Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/DHS_Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Contact__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/DHS_Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Lead__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Assigned_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Name__c</fullName>
    <formula>DHS_Assigned_To__r.FirstName + &apos; &apos; + DHS_Assigned_To__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipName>DHS_Case_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipName>DHS_Contact_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/FOREIGN_ACTIVITIES__c.field-meta.xml
<CustomField>
    <fullName>FOREIGN_ACTIVITIES__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FOREIGN ACTIVITIES</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/FOREIGN_CONTACTS__c.field-meta.xml
<CustomField>
    <fullName>FOREIGN_CONTACTS__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FOREIGN CONTACTS</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject Recontact (SUBC)</fullName>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Publicly Available Electronic Information (PAEI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/recordTypes/Unemployment.recordType-meta.xml
<RecordType>
    <fullName>Unemployment</fullName>
    <active>true</active>
    <label>Unemployment</label>
</RecordType>

force-app/main/default/objects/DHS_Lead_RTA_Extension__c/DHS_Lead_RTA_Extension__c.object-meta.xml
<CustomObject>
    <label>Lead RTA Extension</label>
    <nameField>
        <displayFormat>LeadRTAExt-{00000}</displayFormat>
        <label>Lead RTA Extension Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead RTA Extensions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Lead_RTA_Extension__c/fields/DHS_Lead__c.field-meta.xml
<CustomField>
    <fullName>DHS_Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>DHS_Lead__c</referenceTo>
    <relationshipLabel>Lead RTA Extensions</relationshipLabel>
    <relationshipName>DHS_Lead_RTA_Extensions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHS_Lead_RTA_Extension__c/fields/Foreign_Activities__c.field-meta.xml
<CustomField>
    <fullName>Foreign_Activities__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Foreign Activities</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Lead_RTA_Extension__c/fields/Foreign_Contacts__c.field-meta.xml
<CustomField>
    <fullName>Foreign_Contacts__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Foreign Contacts</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Lead_RTA_Extension__c/fields/Foreign_Travel1__c.field-meta.xml
<CustomField>
    <fullName>Foreign_Travel1__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Foreign Travel1</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Lead_RTA_Extension__c/fields/Foreign_Travel2__c.field-meta.xml
<CustomField>
    <fullName>Foreign_Travel2__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Foreign Travel2</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DHSROIReportController.cls
/**
 * @description Builds the DHS ROI report data model for a selected case.
 */
@SuppressWarnings('PMD.ApexSOQLInjection,PMD.AvoidDeeplyNestedIfStmts,PMD.CognitiveComplexity,PMD.CyclomaticComplexity,PMD.ExcessivePublicCount,PMD.NcssCount,PMD.NcssMethodCount,PMD.StdCyclomaticComplexity')
public with sharing class DHSROIReportController {
    /** @description Provides this DHS API member. */
    public string caseId {get;set;}
    /** @description Provides this DHS API member. */
    public DHS_Case__c caseRecord {get;set;}
    /** @description Provides this DHS API member. */
    public List<DHS_Lead__c> leads {get;set;}
    /** @description Provides this DHS API member. */
    public user currentUser{get;set;}
    /** @description Provides this DHS API member. */
    public integer totalLeads {get;set;}
    /** @description Provides this DHS API member. */
    public String investigationDates {get;set;}
    /** @description Provides this DHS API member. */
    public String investigators {get;set;}
    /** @description Provides this DHS API member. */
    public map<string,integer> leadsCountMap {get;set;}
    /** @description Provides this DHS API member. */
    public map<string,DHS_Lead__c> leadsMap {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> subjectInterviewList {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> subjectContactList {get;set;}
    /** @description Provides this DHS API member. */
    public Map<String,Map<String,List<String>>> employmentMap {get;set;}
    /** @description Provides this DHS API member. */
    public Map<String,Map<String,List<String>>> educationMap {get;set;}
    /** @description Provides this DHS API member. */
    public Map<String,Map<String,List<String>>> medicalMap {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> residenceList {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> referencesList {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> generalLeadsList {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> formerSpouseList {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> unEmploymentList {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> lawEnforcementList {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> financialList {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> employmentList {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> educationList {get;set;}
    /** @description Provides this DHS API member. */
    public List<String> medicalList {get;set;}
    
    

    /** @description Provides this DHS API member. */
    public DHSROIReportController(){
        currentUser = [Select Id, User_Type__c FROM User where Id=:userinfo.getUserId() WITH SECURITY_ENFORCED];
        caseId = String.valueOf(Id.valueOf(ApexPages.currentPage().getParameters().get('id').escapeHtml4()));
        leadsCountMap = new map<string,integer>();
        totalLeads= 0;
        fetchCaseInformation();
        fetchLeadInformation();
    }
    
    /** @description Provides this DHS API member. */
    public void fetchCaseInformation(){
        List<string> caseFields = new List<string>();
        List<DHSApexUtil.Criteria> whereCriteria = new List<DHSApexUtil.Criteria>();
        caseFields = DHSApexUtil.FetchFields('DHS_Case__c');
        caseFields.add('DHS_Contact__r.First_Name__c');
        caseFields.add('DHS_Contact__r.Last_Name__c');
        caseFields.add('DHS_Contact__r.Email__c');
        caseFields.add('DHS_Contact__r.Address__c');
        caseFields.add('DHS_Contact__r.City__c');
        caseFields.add('DHS_Contact__r.State__c');
        caseFields.add('DHS_Contact__r.Zip__c');
        caseFields.add('DHS_Contact__r.SSN__c');
        String query = 'Select '+string.join(caseFields, ',') + ' From DHS_Case__c ';
        
        if(String.isNotBlank(caseId)){
            whereCriteria.add(new DHSApexUtil.Criteria('Id',caseId,'='));
        }
        
        String whereCond = DHSApexUtil.generateWhereQuery(whereCriteria);    
        query = query + ' WHERE '+whereCond+ ' WITH SECURITY_ENFORCED'; 
        // code-analyzer-suppress-next-line PMD.ApexSOQLInjection -- Schema-validated fields and bound or validated values.
        list<DHS_Case__c> cases = database.query(query);
        if(!cases.isEmpty()){
            caseRecord = cases[0];
            if(caseRecord.Investigations_Review_Date__c != Null && caseRecord.QA_and_Review_Date__c != Null){
                DateTime fromDate = DateTime.newInstance(caseRecord.Investigations_Review_Date__c.year(), caseRecord.Investigations_Review_Date__c.month(),caseRecord.Investigations_Review_Date__c.day());
                String fromDateFormatted = fromDate.format('MM/dd/yyyy');
                DateTime toDate = DateTime.newInstance(caseRecord.QA_and_Review_Date__c.year(), caseRecord.QA_and_Review_Date__c.month(),caseRecord.QA_and_Review_Date__c.day());
                String toDateFormatted = toDate.format('MM/dd/yyyy');
                investigationDates = fromDateFormatted +' to '+ toDateFormatted;  
            } 
        }    
    }
    
    /** @description Provides this DHS API member. */
    PUBLIC Map<String, DHS_Lead_RTA_Extension__c> subjectInterviewNLeadRTAExtension {get;set;}
    /** @description Provides this DHS API member. */
    public void fetchLeadInformation(){
        leadsMap = new Map<String,DHS_Lead__c>();
        subjectInterviewNLeadRTAExtension = new Map<String, DHS_Lead_RTA_Extension__c>();
        leads = new List<DHS_Lead__c> ();
        List<string> leadFields = new List<string>();
        List<DHSApexUtil.Criteria> whereCriteria = new List<DHSApexUtil.Criteria>();
        leadFields = DHSApexUtil.FetchFields('DHS_Lead__c');  
        leadFields.add('DHS_Contact__r.First_Name__c');    
        leadFields.add('DHS_Contact__r.Last_Name__c');   
        String query = 'Select '+string.join(leadFields, ',') + ' From DHS_Lead__c ';
        
        if(String.isNotBlank(string.valueof(caseId))){
            whereCriteria.add(new DHSApexUtil.Criteria('DHS_Case__c',caseId,'='));
        }
        
        String whereCond = DHSApexUtil.generateWhereQuery(whereCriteria);    
        query = query + ' WHERE '+whereCond+ ' WITH SECURITY_ENFORCED ORDER BY LeadType__c Asc'; 
        
        // code-analyzer-suppress-next-line PMD.ApexSOQLInjection -- Schema-validated fields and bound or validated values.
        leads = database.query(query);
        List<string> esiLeadIds = new List<String>();
        for(DHS_Lead__c lc: leads){
            if(lc.LeadType__c == 'Subject Interview (ESI/TESI)'){
                esiLeadIds.add(lc.id);
            }
        }
        
        List<DHS_Lead_RTA_Extension__c> leadRTAExtensions = [Select Id, DHS_Lead__c, Foreign_Activities__c, Foreign_Contacts__c, Foreign_Travel1__c, Foreign_Travel2__c
                                                         FROM DHS_Lead_RTA_Extension__c
                                                         WHERE DHS_Lead__c IN:esiLeadIds WITH SECURITY_ENFORCED];
        
        for(DHS_Lead_RTA_Extension__c lrta: leadRTAExtensions){
            subjectInterviewNLeadRTAExtension.put(lrta.DHS_Lead__c, lrta);
        }  
        
        for(String str: esiLeadIds){
            if(!subjectInterviewNLeadRTAExtension.keyset().contains(str)){
                subjectInterviewNLeadRTAExtension.put(str, new DHS_Lead_RTA_Extension__c());
            }
        }                                                
        
        for(DHS_Lead__c l: leads){
            if(!leadsCountMap.containsKey(l.LeadType__c)){
                leadsCountMap.put(l.LeadType__c, 1);    
            }else{
                leadsCountMap.put(l.LeadType__c, leadsCountMap.get(l.LeadType__c)+1);    
            }
            totalLeads++;
            
            string assignedDate;
            if(l.Assignee_Date__c != Null){
             assignedDate = l.Assignee_Date__c.year()+'-'+l.Assignee_Date__c.month()+'-'+l.Assignee_Date__c.day();
            }
            string completedDate;
            if(l.Completed_Date__c != Null){
             completedDate= l.Completed_Date__c.year()+'-'+l.Completed_Date__c.month()+'-'+l.Completed_Date__c.day();
            }
            
            /*if(investigationDates != Null){
                investigationDates =investigationDates+','+assignedDate+' to '+completedDate;
            }else{
                investigationDates =assignedDate+' to '+completedDate;
            }*/
            if(investigators != Null){
                if(l.Assigned_To_Name__c != Null){
                    if(!investigators.contains(l.Assigned_To_Name__c)){
                        investigators = investigators +', '+l.Assigned_To_Name__c;
                    }
                }
            }else{
                investigators = l.Assigned_To_Name__c;
            }
            leadsMap.put(l.id,l);
        }
         employmentMap = new Map<String,Map<String,List<String>>>();
        educationMap = new Map<String,Map<String,List<String>>>();
        medicalMap = new Map<String,Map<String,List<String>>> ();
        subjectInterviewList = new List<String>();
        subjectContactList = new List<String>();
        residenceList = new List<String>();
        referencesList = new List<String>();
        generalLeadsList = new List<String>();
        formerSpouseList = new List<String>();
        unEmploymentList = new List<String>();
        lawEnforcementList = new List<String>();
        financialList = new List<String>();
        employmentList = new list<string>();
        educationList= new list<string>();
        medicalList= new list<string>();
        
        for(DHS_Lead__c l: leads){
            if(l.LeadType__c == 'Employment (EMPL)'){
                employmentList.add(l.id);
            }
            if(l.LeadType__c == 'Education (EDUC)'){
                educationList.add(l.id);
            }
             if(l.LeadType__c == 'Medical (MEDI)'){
                medicalList.add(l.id);
            }
            if(l.LeadType__c == 'Subject Interview (ESI/TESI)'){
                subjectInterviewList.add(l.id);
            }
            if(l.LeadType__c == 'Subject Recontact (SUBC)'){
                subjectContactList.add(l.id);
            }
            
            if(l.LeadType__c == 'Residence (RESI)'){
                residenceList.add(l.id);
            }
            if(l.LeadType__c == 'References (REFE)'){
                referencesList.add(l.id);
            }
            if(l.LeadType__c == 'General (GENL)'){
                generalLeadsList.add(l.id);
            }
            if(l.LeadType__c == 'Former Spouse (FMSP)'){
                formerSpouseList.add(l.id);
            }
            if(l.LeadType__c == 'Unemployment'){
                unEmploymentList.add(l.id);
            }
            if(l.LeadType__c == 'Law Enforcement (LAWE)'){
                lawEnforcementList.add(l.id);
            }
            if(l.LeadType__c == 'Financial (FINL)'){
                financialList.add(l.id);
            }
       
        }

    }
}