force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>DHS_Contact_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/Subject_Name__c.field-meta.xml
<CustomField>
    <fullName>Subject_Name__c</fullName>
    <formula>DHS_Contact__r.Last_Name__c + &apos; &apos; +DHS_Contact__r.First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subject Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/DHS_Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Document__c/DHS_Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{000000}</displayFormat>
        <label>Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Document__c/fields/Added_By__c.field-meta.xml
<CustomField>
    <fullName>Added_By__c</fullName>
    <label>Added By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_Document__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>DHS_Case_Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DHSSubjectFileUploadPageController.cls
/**
 * @description Saves a subject-uploaded file as a DHS case document.
 */
@SuppressWarnings('PMD.UnusedMethod')
public without sharing class DHSSubjectFileUploadPageController {
    /** @description Provides this DHS API member. */
    public string caseId{get;set;}
    /** @description Provides this DHS API member. */
    public string caseRecordIDforDocUpload{get;set;}
    public ApexPages.StandardController controller;
    /** @description Provides this DHS API member. */
    public DHSSubjectFileUploadPageController(){
    	String requestedCaseId = apexpages.currentpage().getparameters().get('caseid');
        caseId = String.isBlank(requestedCaseId)
            ? null
            : String.valueOf(Id.valueOf(requestedCaseId));
        caseRecordIDforDocUpload = caseId;    
    }
     /**
      * @description Provides this DHS API member.
      * @param controller Method parameter.
      */
     public DHSSubjectFileUploadPageController (ApexPages.StandardController controller) {
        this.controller = controller;
     }
    
     /**
      * @description Provides this DHS API member.
      * @return The requested result.
      */
     public PageReference saveAndRedirect() {
         DHS_Case__c caseRecord;
         List<DHS_Case__c> cases = [Select Subject_Name__c,Subject_Type__c,Case_Number__c ,Case_Type__c, DHS_Contact__r.SSN__c from DHS_Case__c where Id=: caseId WITH USER_MODE ];
        if(!cases.isEMpty()){
           caseRecord = cases[0];
        }
         Attachment d = (Attachment) controller.getRecord();
         DHS_Document__c document = new DHS_Document__c();
         document.Added_By__c = caseRecord.Subject_Name__c;
         document.DHS_Case__c = caseId;
         document.Name__c = d.Name;
		Database.insert(document, AccessLevel.USER_MODE);
	         d.parentid=document.id;
      
              controller.save();
         return null;
     }
}