force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>DHS_Contact_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/DHS_Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investigator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Daily_Production_Summary__c/DHS_Daily_Production_Summary__c.object-meta.xml
<CustomObject>
    <label>Daily Production Summary</label>
    <nameField>
        <displayFormat>DPS-{000000}</displayFormat>
        <label>Daily Production Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Production Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Daily_Production_Summary__c/fields/DHS_Reviewer__c.field-meta.xml
<CustomField>
    <fullName>DHS_Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Daily_Production_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/DHS_Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Lead__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Subject Interview</fullName>
            </value>
            <value>
                <fullName>General Record</fullName>
            </value>
            <value>
                <fullName>Subject Recontact</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipName>DHS_Case_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipName>DHS_Contact_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject Recontact (SUBC)</fullName>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Publicly Available Electronic Information (PAEI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Reason_for_Waiver__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Waiver__c</fullName>
    <label>Reason for Waiver</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject not available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DHSLeadDashboardControllerTest.cls
@isTest
/** Exercises the existing DHSLeadDashboardController behavior. */
@SuppressWarnings('PMD.AnnotationsNamingConventions, PMD.LocalVariableNamingConventions, PMD.ApexUnitTestClassShouldHaveRunAs, PMD.MethodNamingConventions')
public class DHSLeadDashboardControllerTest {
     @testSetup static void setup() {
         User pmoUser = PPFDHSTestUserFactory.createPmoUser();
         System.runAs(pmoUser) {
         DHS_Contact__c con = new DHS_Contact__c();
         con.First_Name__c = 'Test';
         
         con.Last_Name__c = 'Name';
         con.Email__c  = 'test@test.com';
         con.Contact_Type__c = 'Subject';
         con.SSN__c = '123-12-1123';
         insert con;
         DHS_Case__c CaseTemp = new DHS_Case__c();
         CaseTemp.DHS_Contact__c = con.id;
         CaseTemp.DHS_Assigned_To__c = userinfo.getuserId();
         insert CaseTemp;
         DHS_Lead__c Lead = new DHS_Lead__c();
         Lead.DHS_Case__c = CaseTemp.id;
         
         Lead.DHS_Assigned_To__c = userinfo.getuserid();
         Lead.Coverage_Type__c = 'Subject Interview';
         Lead.LeadType__c = 'Subject Interview (ESI/TESI)';
         insert Lead;
         lead.Reason_for_Waiver__c = 'Subject not available';
         update lead;
         insert new DHS_Daily_Production_Summary__c(
             DHS_Reviewer__c = UserInfo.getUserId(),
             Leads_Accepted__c = 0,
             Leads_Rejected__c = 0
         );
         }
     }
    @IsTest private static void testConstructorSearchParameters(){
        System.runAs(PPFDHSTestUserFactory.getPmoUser()) {
        PageReference LeadDashboardPage = Page.DHSLeaddashboard;
        Test.setCurrentPage(LeadDashboardPage);
        LeadDashboardPage.getParameters().put('searchUnassigned','false'); 
        LeadDashboardPage.getParameters().put('ZipSearchEntry','test'); 
        LeadDashboardPage.getParameters().put('stateSearchEntry','test'); 
        LeadDashboardPage.getParameters().put('citySearchEntry','test'); 
        LeadDashboardPage.getParameters().put('subjectLastNameSearchEntry','test'); 
        LeadDashboardPage.getParameters().put('manifestSearchEntry','test'); 
        LeadDashboardPage.getParameters().put('subjectFirstNameSearchEntry','test'); 
        LeadDashboardPage.getParameters().put('caseNumberSearchEntry','test'); 
        LeadDashboardPage.getParameters().put('leadStatusSearchEntry','test'); 
        LeadDashboardPage.getParameters().put('leadTypeSearchEntry','test'); 
        DHSLeadDashboardController leadDashboardCtrl = new DHSLeadDashboardController();
        System.assertNotEquals(null, leadDashboardCtrl.leadsSearched, 'Assertion failed in DHSLeadDashboardControllerTest at source line 51');
        }
    }

    @IsTest private static void testSearchAndAssignment(){
        System.runAs(PPFDHSTestUserFactory.getPmoUser()) {
        Test.setCurrentPage(Page.DHSLeaddashboard);
        DHSLeadDashboardController leadDashboardCtrl = new DHSLeadDashboardController();
        leadDashboardCtrl.searchUnassigned = true;
        leadDashboardCtrl.SearchAction();
        system.assertEquals(1,leadDashboardCtrl.leadsSearched.size(), 'Assertion failed in DHSLeadDashboardControllerTest at source line 61');
        leadDashboardCtrl.selectedUserIdForAssignment = userinfo.getUserId();
        leadDashboardCtrl.leadsSearched[0].isSelected = true;
        leadDashboardCtrl.AssignLeadsAction();
        }
    }

    @IsTest private static void testLeadActions(){
        System.runAs(PPFDHSTestUserFactory.getPmoUser()) {
        Test.setCurrentPage(Page.DHSLeaddashboard);
        DHSLeadDashboardController leadDashboardCtrl = new DHSLeadDashboardController();
        leadDashboardCtrl.searchUnassigned = true;
        leadDashboardCtrl.SearchAction();
        System.assertEquals(1, leadDashboardCtrl.leadsSearched.size(), 'Assertion failed in DHSLeadDashboardControllerTest at source line 74');
        leadDashboardCtrl.leadsSearched[0].isSelected = true;
        leadDashboardCtrl.leadIdToUpdate = leadDashboardCtrl.leadsSearched[0].ld.Id;
        leadDashboardCtrl.acdDateToUpdate = 'invalid-date';
        leadDashboardCtrl.UpdateACDLead();
        System.assertNotEquals(null, leadDashboardCtrl.errorMessage, 'Assertion failed in DHSLeadDashboardControllerTest at source line 79');
        leadDashboardCtrl.onstatechange();
        leadDashboardCtrl.searchUnassigned = false;
        leadDashboardCtrl.seachqarejected = true;
        leadDashboardCtrl.SearchAction();
        leadDashboardCtrl.UnAssignLeadsAction();
        }
    }

    @IsTest private static void testUpdateAndPagination(){
        System.runAs(PPFDHSTestUserFactory.getPmoUser()) {
        Test.setCurrentPage(Page.DHSLeaddashboard);
        DHSLeadDashboardController leadDashboardCtrl = new DHSLeadDashboardController();
        leadDashboardCtrl.searchUnassigned = true;
        leadDashboardCtrl.SearchAction();
        system.assertEquals(1,leadDashboardCtrl.leadsSearched.size(), 'Assertion failed in DHSLeadDashboardControllerTest at source line 94');
        leadDashboardCtrl.leadsSearched[0].isSelected = true;
        leadDashboardCtrl.anticipatedCompletionDate = system.today();
        leadDashboardCtrl.updateACDDate();
        leadDashboardCtrl.handlePrev();
        leadDashboardCtrl.handleNext();
        List<id> ids = New List<id>();
        DHS_Lead__c l = [select id from DHS_Lead__c limit 1];
        ids.add(l.Id);
        DHSLeadDashboardController.updateleadsunassignmethod(ids);
        }
    }

    @IsTest private static void testNavigationConstructorModes(){
        System.runAs(PPFDHSTestUserFactory.getPmoUser()) {
        PageReference dashboardPage = Page.DHSLeaddashboard;
        Test.setCurrentPage(dashboardPage);
        dashboardPage.getParameters().put('searchmyavailableleads', 'true');
        DHSLeadDashboardController availableController = new DHSLeadDashboardController();
        System.assertNotEquals(null, availableController.leadsSearched, 'Assertion failed in DHSLeadDashboardControllerTest at source line 113');
        dashboardPage.getParameters().clear();
        dashboardPage.getParameters().put('searchmyAssigned', 'true');
        DHSLeadDashboardController assignedController = new DHSLeadDashboardController();
        System.assertNotEquals(null, assignedController.leadsSearched, 'Assertion failed in DHSLeadDashboardControllerTest at source line 117');
        }
    }

    @IsTest private static void testAdditionalSearchModes(){
        System.runAs(PPFDHSTestUserFactory.getPmoUser()) {
        Test.setCurrentPage(Page.DHSLeaddashboard);
        DHSLeadDashboardController leadDashboardCtrl = new DHSLeadDashboardController();
        leadDashboardCtrl.searchQARejected = true;
        leadDashboardCtrl.SearchAction();
        leadDashboardCtrl.searchQARejected = false;
        leadDashboardCtrl.searchmydiscontinued = true;
        leadDashboardCtrl.SearchAction();
        leadDashboardCtrl.searchmydiscontinued = false;
        leadDashboardCtrl.seachqarejected = true;
        leadDashboardCtrl.SearchAction();
        System.assertNotEquals(null, leadDashboardCtrl.leadsSearched, 'Assertion failed in DHSLeadDashboardControllerTest at source line 133');
        }
    }

    @IsTest private static void testAcceptAction(){
        System.runAs(PPFDHSTestUserFactory.getPmoUser()) {
        Test.setCurrentPage(Page.DHSLeaddashboard);
        DHSLeadDashboardController leadDashboardCtrl = new DHSLeadDashboardController();
        leadDashboardCtrl.searchUnassigned = true;
        leadDashboardCtrl.SearchAction();
        leadDashboardCtrl.leadIdToAccept = leadDashboardCtrl.leadsSearched[0].ld.Id;
        leadDashboardCtrl.acceptaction();
        System.assertEquals(0, leadDashboardCtrl.leadsSearched.size(), 'Assertion failed in DHSLeadDashboardControllerTest at source line 145');
        }
    }

    @IsTest private static void testRejectAction(){
        System.runAs(PPFDHSTestUserFactory.getPmoUser()) {
        Test.setCurrentPage(Page.DHSLeaddashboard);
        DHSLeadDashboardController leadDashboardCtrl = new DHSLeadDashboardController();
        leadDashboardCtrl.searchUnassigned = true;
        leadDashboardCtrl.SearchAction();
        leadDashboardCtrl.leadIdToReject = leadDashboardCtrl.leadsSearched[0].ld.Id;
        leadDashboardCtrl.rejectaction();
        System.assertEquals(0, leadDashboardCtrl.leadsSearched.size(), 'Assertion failed in DHSLeadDashboardControllerTest at source line 157');
        }
    }
}