force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/DIA_Case__c.object-meta.xml
<CustomObject>
    <label>DIA Case</label>
    <nameField>
        <displayFormat>DIACase-{000000}</displayFormat>
        <label>DIA Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIACases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DIA_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Contact__c/DIA_Contact__c.object-meta.xml
<CustomObject>
    <label>DIA Contact</label>
    <nameField>
        <displayFormat>DIAContact-{000000}</displayFormat>
        <label>DIA Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Contact__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/DIA_Lead__c.object-meta.xml
<CustomObject>
    <label>DIA Lead</label>
    <nameField>
        <displayFormat>DIALead-{000000}</displayFormat>
        <label>DIA Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Lead__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIA_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipName>DIA_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DIA_Contact__c</referenceTo>
    <relationshipName>DIA_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Subject Interview</fullName>
            </value>
            <value>
                <fullName>General Record</fullName>
            </value>
            <value>
                <fullName>Subject Recontact</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject contact (SUBC)</fullName>
                <label>Subject Recontact (SUBC)</label>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DIAHeaderControllerTest.cls
@isTest
public class DIAHeaderControllerTest {
    @testSetup static void setup() {
        
         DIA_Contact__c con = new DIA_Contact__c();
         con.first_name__c = 'Test';
         con.last_name__c = 'Name';
         con.Email__c  = 'test@test.com';
         con.Contact_Type__c = 'Subject';
         con.ssn__c = '123-12-1123';
         insert con;
         DIA_Case__c diaCase = new DIA_Case__c();
         diaCase.contact__c = con.id;
         diaCase.Assigned_To__c = userinfo.getuserId();
         insert diaCase;
         DIA_Lead__c diaLead = new DIA_Lead__c();
         diaLead.case__c = diaCase.id;
         //diaLead.Assigned_To__c = userinfo.getuserid();
         diaLead.Coverage_Type__c = 'Subject Interview';
         diaLead.LeadType__c = 'Subject Interview (ESI/TESI)';
         insert diaLead;
     }
     testMethod private static void TestMethod1(){
       DIAHeaderController  ctrl = new DIAHeaderController ();
        user currentUser = [Select Id, User_Type__c from User where Id=:userinfo.getuserid()];
        currentUser.User_Type__c = 'CMO';
        update currentUser;
        DIAHeaderController  ctrl2 = new DIAHeaderController ();
        currentUser = [Select Id, User_Type__c from User where Id=:userinfo.getuserid()];
        currentUser.User_Type__c = 'QA';
        update currentUser;
        DIAHeaderController  ctrl3 = new DIAHeaderController ();
        currentUser = [Select Id, User_Type__c from User where Id=:userinfo.getuserid()];
        currentUser.User_Type__c = 'INV';
        update currentUser;
        DIAHeaderController  ctrl5 = new DIAHeaderController ();
        currentUser = [Select Id, User_Type__c from User where Id=:userinfo.getuserid()];
        currentUser.User_Type__c = 'PMO';
        update currentUser;
        DIAHeaderController  ctrl4 = new DIAHeaderController ();
                 
     }
}