force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 5</fullName>
            </value>
            <value>
                <fullName>Tier 5 Reinvestigation</fullName>
            </value>
            <value>
                <fullName>Triggered Investigation</fullName>
            </value>
            <value>
                <fullName>Supplemental Investigation</fullName>
            </value>
            <value>
                <fullName>High Tier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/costpoint_code__c.field-meta.xml
<CustomField>
    <fullName>costpoint_code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>costpoint code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Service_Days__c.field-meta.xml
<CustomField>
    <fullName>Service_Days__c</fullName>
    <label>Service Days</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Case_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>40</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Invoice-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <formula>Case__r.Case_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <formula>TEXT(Case__r.Case_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Costpoint_Code__c.field-meta.xml
<CustomField>
    <fullName>Costpoint_Code__c</fullName>
    <formula>Case__r.costpoint_code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Costpoint Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Interview_Method__c.field-meta.xml
<CustomField>
    <fullName>Interview_Method__c</fullName>
    <label>Interview Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>P-UC</fullName>
            </value>
            <value>
                <fullName>PO</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>R-UC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <formula>Lead__r.Item_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case__c</referenceTo>
    <relationshipName>Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Subject Interview</fullName>
            </value>
            <value>
                <fullName>General Record</fullName>
            </value>
            <value>
                <fullName>Subject Recontact</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject contact (SUBC)</fullName>
                <label>Subject Recontact (SUBC)</label>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Publicly Available Electronic Information (PAEI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Personal_Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Personal_Contact_Method__c</fullName>
    <label>Personal Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>By Telephone/Fax</fullName>
                <isActive>false</isActive>
                <label>By Telephone/Fax</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OnBoarding__c/OnBoarding__c.object-meta.xml
<CustomObject>
    <label>OnBoarding</label>
    <nameField>
        <displayFormat>user-{000000}</displayFormat>
        <label>OnBoarding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OnBoarding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OnBoarding__c/fields/Candidate_type__c.field-meta.xml
<CustomField>
    <fullName>Candidate_type__c</fullName>
    <label>Candidate type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>SCA</fullName>
            </value>
            <value>
                <fullName>Non-SCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OnBoarding__c/fields/Paychex_ID__c.field-meta.xml
<CustomField>
    <fullName>Paychex_ID__c</fullName>
    <label>ADP File Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OnBoarding__c/fields/Send_Credentials_To_User__c.field-meta.xml
<CustomField>
    <fullName>Send_Credentials_To_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Credentials To User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OnBoarding__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OnBoarding__c/fields/System_Access__c.field-meta.xml
<CustomField>
    <fullName>System_Access__c</fullName>
    <label>System Access</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intel</fullName>
            </value>
            <value>
                <fullName>DIA</fullName>
                <label>BI</label>
            </value>
            <value>
                <fullName>DHS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OnBoarding__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OnBoarding</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OnBoarding__c/fields/User_Profile__c.field-meta.xml
<CustomField>
    <fullName>User_Profile__c</fullName>
    <label>User Profile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PMO</fullName>
            </value>
            <value>
                <fullName>CMO</fullName>
            </value>
            <value>
                <fullName>INV</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Customer User</fullName>
            </value>
            <value>
                <fullName>Case Manager</fullName>
                <isActive>false</isActive>
                <label>Case Manager</label>
            </value>
            <value>
                <fullName>Investigator</fullName>
                <isActive>false</isActive>
                <label>Investigator</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceModuleControllerTest.cls
@IsTest
/** Exercises the existing InvoiceModuleController behavior. */
@SuppressWarnings('PMD.ExcessiveParameterList, PMD.NcssCount')
private class InvoiceModuleControllerTest {

    @IsTest
    static void fetchInvoiceRecordsReturnsGeneratedInvoiceForSelectedWorker() {
        User pmoUser;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            pmoUser = createUser('pmo', 'PMO', 'Employee');
        }

        Account intelAccount = new Account(
                Name = System.Label.IntelAccountName
            );
            insert intelAccount;

            Contact__c subject = new Contact__c(
                First_Name__c = 'Subject',
                Last_Name__c = 'Smith',
                Email__c = 'subject@example.com',
                Contact_Type__c = 'Subject',
                SSN__c = '123-45-6789'
            );
            insert subject;

            Case__c caseRecord = new Case__c(
                Contact__c = subject.Id,
                Assigned_To__c = pmoUser.Id,
                Case_Number__c = 'TEST1234',
                Case_Type__c = 'Tier 5',
                Service_Days__c = '40',
                Status__c = 'Active',
                Costpoint_Code__c = '3207.C01.0008.T1'
            );
            insert caseRecord;

            OnBoarding__c onboardingRecord = new OnBoarding__c(
                First_Name__c = 'Jason',
                Last_Name__c = 'Stott',
                Email__c = 'jason.stott@example.com',
                User__c = pmoUser.Id,
                User_Profile__c = 'PMO',
                Candidate_Type__c = 'Employee',
                System_Access__c = 'Intel',
                Status__c = 'Active',
                Send_Credentials_To_User__c = false,
                Paychex_ID__c = '12345'
            );
            insert onboardingRecord;

            Lead__c completedLead = createLead(
                caseRecord.Id,
                subject.Id,
                pmoUser.Id,
                'Subject Interview (ESI/TESI)',
                'Subject Interview',
                3
            );
            completedLead.Was_Subject_interview_conducted__c = 'Yes';
            insert completedLead;

            Lead__c rejectedLead = createLead(
                caseRecord.Id,
                subject.Id,
                pmoUser.Id,
                'General (GENL)',
                'Personal',
                6
            );
            rejectedLead.Was_the_record_obtained_Personal__c =
                'Yes, Source was interviewed';
            rejectedLead.Personal_Contact_Method__c = 'Telephone';
            insert rejectedLead;

            Date payPeriodEndingDate = Date.today();

        System.runAs(pmoUser) {
            Invoice__c generatedInvoice = new Invoice__c(
                Lead__c = completedLead.Id,
                Status__c = 'Generated',
                Pay_Period_Ending__c = payPeriodEndingDate
            );
            insert generatedInvoice;

            // This record must not be returned.
            Invoice__c nonGeneratedInvoice = new Invoice__c(
                Lead__c = rejectedLead.Id,
                Status__c = 'In-Review',
                Pay_Period_Ending__c = payPeriodEndingDate
            );
            insert nonGeneratedInvoice;

            InvoiceModuleController controller =
                new InvoiceModuleController();
            controller.selectedUserOption = 'Employee';
            controller.RefreshWorkerOptions();
            controller.handlePrev();
            controller.handleNext();

            /*
             * Use All here because the controller's Employee filter uses:
             * Lead__r.Assigned_To__r.Contact.OnBoarding__r.Candidate_Type__c
             *
             * The test user is an internal user and therefore does
             * not have a ContactId.
             */
            controller.selectedUserOption = 'All';
            controller.selectedWorkerId = pmoUser.Id;
            controller.selectedCycleFilterDate =
                String.valueOf(payPeriodEndingDate);

            Test.startTest();
            controller.FetchInvoiceRecords();
            Test.stopTest();

            System.assertEquals(
                true,
                controller.isPMOUser,
                'The test user should be recognized as a PMO user.'
            );
            System.assertEquals(
                1,
                controller.invoices.size(),
                'Only one generated invoice should match the filters.'
            );
            System.assertEquals(
                generatedInvoice.Id,
                controller.invoices[0].Id,
                'The generated invoice for the selected worker should return.'
            );
            System.assertEquals(
                1,
                controller.totalRecordCount
            , 'Assertion failed in InvoiceModuleControllerTest at source line 132');
            System.assertEquals(
                1,
                controller.totalPages
            , 'Assertion failed in InvoiceModuleControllerTest at source line 136');
            System.assertEquals(
                1,
                controller.currentRecordCount
            , 'Assertion failed in InvoiceModuleControllerTest at source line 140');
            System.assertEquals(
                true,
                controller.disablePrev
            , 'Assertion failed in InvoiceModuleControllerTest at source line 144');
            System.assertEquals(
                true,
                controller.disableNext
            , 'Assertion failed in InvoiceModuleControllerTest at source line 148');
            System.assertNotEquals(
                null,
                InvoiceModuleController.criteria
            , 'Assertion failed in InvoiceModuleControllerTest at source line 152');
            controller.queryForNextRecords =
                'SELECT Id, Name FROM Invoice__c WHERE Id != null AND';
            controller.firstRecordName = 'zzzz';
            controller.lastRecordName = '0';
            controller.pageNumber = 2;
            controller.totalRecordCount = 401;
            controller.disableNext = false;
            controller.handlePrev();
            controller.handleNext();
        }
    }

    @IsTest
    static void fetchInvoiceRecordsReturnsNothingForNonPmoUser() {
        User employeeUser = createUser(
            'employee',
            'INV',
            'Employee'
        );

        System.runAs(employeeUser) {
            InvoiceModuleController controller =
                new InvoiceModuleController();

            Test.startTest();
            controller.FetchInvoiceRecords();
            Test.stopTest();

            System.assertEquals(false, controller.isPMOUser, 'Assertion failed in InvoiceModuleControllerTest at source line 184');
            System.assertEquals(0, controller.invoices.size(), 'Assertion failed in InvoiceModuleControllerTest at source line 185');
            System.assertEquals(0, controller.totalRecordCount, 'Assertion failed in InvoiceModuleControllerTest at source line 186');
        }
    }

    @IsTest
    static void generateInvoiceRecordsBatchCreatesInvoiceForCompletedLead() {
        User investigator;
        System.runAs(new User(Id = UserInfo.getUserId())) {
            investigator = createUser('batchinv', 'INV', 'Employee');
        }

        Contact__c subject = new Contact__c(
            First_Name__c = 'Batch',
            Last_Name__c = 'Subject',
            Email__c = 'batch.subject@example.com',
            Contact_Type__c = 'Subject',
            SSN__c = '987-65-4321'
        );
        insert subject;

        Case__c caseRecord = new Case__c(
            Contact__c = subject.Id,
            Assigned_To__c = investigator.Id,
            Case_Number__c = 'BATCH001',
            Case_Type__c = 'Tier 5',
            Service_Days__c = '40',
            Status__c = 'Active',
            Costpoint_Code__c = '3207.C01.0008.T1'
        );
        insert caseRecord;

        Lead__c completedLead = createLead(
            caseRecord.Id,
            subject.Id,
            investigator.Id,
            'Subject Interview (ESI/TESI)',
            'Subject Interview',
            20
        );
        completedLead.Was_Subject_interview_conducted__c = 'Yes';
        insert completedLead;

        completedLead.Status__c = 'Completed';

        Test.startTest();
        GenerateInvoiceRecordsBatch invoiceBatch =
            new GenerateInvoiceRecordsBatch();
        System.assertNotEquals(null, invoiceBatch.start(null), 'Assertion failed in InvoiceModuleControllerTest at source line 233');
        System.runAs(investigator) {
            invoiceBatch.execute(null, new List<Lead__c>{ completedLead });
            invoiceBatch.finish(null);
        }
        Test.stopTest();

        System.runAs(investigator) {
            List<Invoice__c> generatedInvoices = [
                SELECT Lead__c, Case__c, Interview_Method__c, Item_Price__c,
                    Status__c, Pay_Period_Ending__c
                FROM Invoice__c
                WHERE Lead__c = :completedLead.Id
            ];
            System.assertEquals(1, generatedInvoices.size(), 'Assertion failed in InvoiceModuleControllerTest at source line 247');
            System.assertEquals(caseRecord.Id, generatedInvoices[0].Case__c, 'Assertion failed in InvoiceModuleControllerTest at source line 248');
            System.assertEquals('P', generatedInvoices[0].Interview_Method__c, 'Assertion failed in InvoiceModuleControllerTest at source line 249');
            System.assertEquals(450, generatedInvoices[0].Item_Price__c, 'Assertion failed in InvoiceModuleControllerTest at source line 250');
            System.assertEquals('Generated', generatedInvoices[0].Status__c, 'Assertion failed in InvoiceModuleControllerTest at source line 251');
            System.assertNotEquals(
                null,
                generatedInvoices[0].Pay_Period_Ending__c
            , 'Assertion failed in InvoiceModuleControllerTest at source line 252');
        }
    }

    private static Lead__c createLead(
        Id caseId,
        Id contactId,
        Id assignedUserId,
        String leadType,
        String coverageType,
        Integer itemNumber
    ) {
        return new Lead__c(
            Case__c = caseId,
            Assigned_To__c = assignedUserId,
            Contact__c = contactId,
            LeadType__c = leadType,
            Coverage_Type__c = coverageType,
            Item_Number__c = itemNumber,
            Completed_Date__c = Date.today()
        );
    }

    private static User createUser(
        String aliasPrefix,
        String userType,
        String candidateType
    ) {
        Profile standardProfile = [
            SELECT Id
            FROM Profile
            WHERE Name = 'Standard User'
            LIMIT 1
        ];

        String uniqueValue =
            String.valueOf(DateTime.now().getTime()) +
            String.valueOf(Crypto.getRandomInteger()).replace('-', '');

        User testUser = new User(
            Alias = aliasPrefix.left(8),
            Email = aliasPrefix + uniqueValue + '@example.com',
            EmailEncodingKey = 'UTF-8',
            LastName = aliasPrefix,
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = standardProfile.Id,
            TimeZoneSidKey = 'America/New_York',
            Username = aliasPrefix + uniqueValue + '@example.com',
            User_Type__c = userType,
            Candidate_Type__c = candidateType,
            System_Access__c = 'Intel'
        );
        insert testUser;

        String permissionSetName = userType == 'PMO'
            ? 'PPF_PMO_PS'
            : 'PPF_INV_PS';
        PermissionSet rolePermissionSet = [
            SELECT Id
            FROM PermissionSet
            WHERE Name = :permissionSetName
            LIMIT 1
        ];
        insert new PermissionSetAssignment(
            AssigneeId = testUser.Id,
            PermissionSetId = rolePermissionSet.Id
        );

        return testUser;
    }
}