force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/DIA_Case__c.object-meta.xml
<CustomObject>
    <label>DIA Case</label>
    <nameField>
        <displayFormat>DIACase-{000000}</displayFormat>
        <label>DIA Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/fields/Assigned_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Name__c</fullName>
    <formula>Assigned_To__r.FirstName  +&apos; &apos; +Assigned_To__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Delivered canceled</fullName>
            </value>
            <value>
                <fullName>Delivered pending item(s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Document__c/DIA_Document__c.object-meta.xml
<CustomObject>
    <label>DIA Document</label>
    <nameField>
        <displayFormat>DIADoc-{000000}</displayFormat>
        <label>DIA Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Document__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIA_Document_Request__c/DIA_Document_Request__c.object-meta.xml
<CustomObject>
    <label>DIA Document Request</label>
    <nameField>
        <displayFormat>DIADR-{0000000}</displayFormat>
        <label>DIA Document Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Document Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Document_Request__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>DIA_Lead__c</referenceTo>
    <relationshipLabel>DIA Document Requests</relationshipLabel>
    <relationshipName>DIA_Document_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIA_Document_Request__c/fields/Request_Expired__c.field-meta.xml
<CustomField>
    <fullName>Request_Expired__c</fullName>
    <formula>NOW() &gt;  DATETIMEVALUE(Expiration_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Request Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIA_Document_Request__c/fields/Subject_Comments__c.field-meta.xml
<CustomField>
    <fullName>Subject_Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Subject Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/DIA_Lead__c.object-meta.xml
<CustomObject>
    <label>DIA Lead</label>
    <nameField>
        <displayFormat>DIALead-{000000}</displayFormat>
        <label>DIA Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Lead__c/fields/Assigned_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Name__c</fullName>
    <formula>Assigned_To__r.FirstName + &apos; &apos; + Assigned_To__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned To Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipName>DIA_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Assigned Not Accepted</fullName>
            </value>
            <value>
                <fullName>Investigator Rejected</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Applied For Waiver</fullName>
            </value>
            <value>
                <fullName>QA Rejected</fullName>
            </value>
            <value>
                <fullName>QA Review Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case__c</referenceTo>
    <relationshipName>Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DIASubjectDocumentsUploadController.cls
public with sharing class DIASubjectDocumentsUploadController{
    public string documentRequestId {get;set;}
    public DIA_Document_Request__c documentRequest {get;set;}
    public boolean showUploadPanel {get;set;}
    public boolean showAfterUploadPanel {get;set;}
    public boolean showExpiryPanel {get;set;}
    public list<attachment> attachmentsList {get;set;}
    
    public DIASubjectDocumentsUploadController(){
        documentRequestId = apexpages.currentpage().getparameters().get('id');
        System.debug('documentRequestId...'+documentRequestId);
        documentRequestId = decodeURLParams(documentRequestId);
        
        FetchDocumentRequest();
    }
    
    public void FetchDocumentRequest(){
        showUploadPanel = false;
        showAfterUploadPanel = false;
        showExpiryPanel = false;
        documentRequest = [Select Id, Lead__c, Lead__r.Assigned_To_Name__c,Lead__r.case__r.Case_Number__c, Expiration_Date__c, CreatedDate, Status__c, Subject_Comments__c, Request_Expired__c from DIA_Document_Request__c WHERE ID=: documentRequestId WITH SECURITY_ENFORCED];
        if(documentRequest.Status__c == 'Documents Requested' && !documentRequest.Request_Expired__c){
            showUploadPanel = true;    
        }
        if(documentRequest.Status__c == 'Documents Received' && !documentRequest.Request_Expired__c){
            showAfterUploadPanel = true;    
        }
        if(documentRequest.Request_Expired__c){
            showExpiryPanel = true;    
        }
        System.debug('showUploadPanel...'+showUploadPanel);
         System.debug('showAfterUploadPanel...'+showAfterUploadPanel);
         System.debug('documentRequest.Status__c...'+documentRequest.Status__c);
         System.debug('documentRequest.Request_Expired__c...'+documentRequest.Request_Expired__c);
        attachmentsList = new list<attachment>();
        attachmentsList = [Select Id, parentId, Name, CreatedDate, Description from Attachment where parentId =:documentRequestId WITH SECURITY_ENFORCED];
    
    }
    
    public void submitaction(){
        documentRequest.Status__c='Documents Received';
        Map<String, Schema.SObjectField> fields = ApexUtil.getObjectFieldsDescribe('DIA_Document_Request__c');
            if(Schema.SobjectType.DIA_Document_Request__c.isUpdateable() &&
                fields.get('Status__c').getDescribe().isAccessible()){

                Database.SaveResult dsr = database.update(documentRequest, false, AccessLevel.USER_MODE);
                if(dsr.isSuccess()){
                    FetchDocumentRequest();
                }
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to update Document Request'));
            }
    }
    public string deleteAttachmentId{get;set;}
    public void DeleteAttachment(){
        Attachment att = [select Id from Attachment where id=:deleteAttachmentId];
        if(Schema.SobjectType.DIA_document__c.isDeletable()){
            Database.DeleteResult drList = database.delete(att, false, AccessLevel.USER_MODE);
            if(drList.isSuccess()){
                FetchDocumentRequest();
            }
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to delete Attachment'));
        }
    }
    
    public void autosaveaction(){
        if(Schema.SobjectType.DIA_Document_Request__c.isUpdateable()){
            Database.SaveResult dsr = database.update(documentRequest, false, AccessLevel.USER_MODE);
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to update Document Request'));
        }
        
    }
    
    private String decodeURLParams(String encodedString){
         // take the base64 encoded parameter and create base64 decoded Blob from it   
         Blob afterblob = EncodingUtil.base64Decode(encodedString);
         // Convert the blob back to a string and print it in the debug log
         System.debug(encodedString + 'is now decoded as: ' + afterblob.toString());
         return afterblob.toString();
        
    }

}