force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Request__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Document Requests</relationshipLabel>
    <relationshipName>Document_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case__c</referenceTo>
    <relationshipName>Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Subject Interview</fullName>
            </value>
            <value>
                <fullName>General Record</fullName>
            </value>
            <value>
                <fullName>Subject Recontact</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject contact (SUBC)</fullName>
                <label>Subject Recontact (SUBC)</label>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Publicly Available Electronic Information (PAEI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubjectDocumentsUploadControllerTest.cls
@IsTest
/** Exercises the PPF subject-document upload lifecycle. */
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
private class SubjectDocumentsUploadControllerTest {
    @IsTest
    static void loadsSubmitsDeletesAndAutosavesRequest() {
        Case__c caseRecord = new Case__c();
        insert caseRecord;
        Lead__c leadRecord = new Lead__c(
            Case__c = caseRecord.Id,
            LeadType__c = 'Subject Interview (ESI/TESI)',
            Coverage_Type__c = 'Subject Interview'
        );
        insert leadRecord;
        Document_Request__c requestRecord = new Document_Request__c(
            Lead__c = leadRecord.Id,
            To_Address__c = 'subject-documents@example.com',
            Status__c = 'Documents Requested'
        );
        insert requestRecord;
        Test.setCurrentPage(new PageReference('/apex/subject-documents-test'));
        ApexPages.currentPage().getParameters().put(
            'id', EncodingUtil.base64Encode(Blob.valueOf(requestRecord.Id))
        );
        SubjectDocumentsUploadController controller =
            new SubjectDocumentsUploadController();
        controller.submitaction();

        Attachment uploadedFile = new Attachment(
            ParentId = requestRecord.Id,
            Name = 'identity.txt',
            Body = Blob.valueOf('test document')
        );
        insert uploadedFile;
        controller.deleteAttachmentId = uploadedFile.Id;
        controller.DeleteAttachment();
        controller.documentRequest.Subject_Comments__c = 'Verified';
        controller.autosaveaction();

        System.assertEquals('Documents Received', controller.documentRequest.Status__c, 'Assertion failed in SubjectDocumentsUploadControllerTest at source line 40');
        System.assertEquals(0, [SELECT COUNT() FROM Attachment WHERE Id = :uploadedFile.Id], 'Assertion failed in SubjectDocumentsUploadControllerTest at source line 41');
    }
}