force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 5</fullName>
            </value>
            <value>
                <fullName>Tier 5 Reinvestigation</fullName>
            </value>
            <value>
                <fullName>Triggered Investigation</fullName>
            </value>
            <value>
                <fullName>Supplemental Investigation</fullName>
            </value>
            <value>
                <fullName>High Tier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/DIA_Case__c.object-meta.xml
<CustomObject>
    <label>DIA Case</label>
    <nameField>
        <displayFormat>DIACase-{000000}</displayFormat>
        <label>DIA Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 5</fullName>
            </value>
            <value>
                <fullName>Tier 5 Reinvestigation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DIA_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Subject_Type__c.field-meta.xml
<CustomField>
    <fullName>Subject_Type__c</fullName>
    <label>Subject Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Contact__c/DIA_Contact__c.object-meta.xml
<CustomObject>
    <label>DIA Contact</label>
    <nameField>
        <displayFormat>DIAContact-{000000}</displayFormat>
        <label>DIA Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Contact__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIA_Document__c/DIA_Document__c.object-meta.xml
<CustomObject>
    <label>DIA Document</label>
    <nameField>
        <displayFormat>DIADoc-{000000}</displayFormat>
        <label>DIA Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Document__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DIAFileUploadPageController.cls
public with sharing class DIAFileUploadPageController {
    public string caseid;
    public DIA_Case__c caseRecord {get;set;}
    public ApexPages.StandardController controller;
    public DIAFileUploadPageController (ApexPages.StandardController controller) {
        this.controller = controller;
        caseId = apexpages.currentpage().getparameters().get('caseid');
        List<DIA_Case__c> cases = [Select Subject_Type__c,Case_Number__c ,case_type__c, Contact__r.SSN__c from DIA_Case__c where Id=: caseId WITH SECURITY_ENFORCED];
        if(!cases.isEMpty()){
           caseRecord = cases[0];
        }
    } 
    public PageReference saveAndRedirect() {
         Attachment d = (Attachment) controller.getRecord();
         DIA_Document__c document = new DIA_Document__c();
         document.added_by__c = [Select Id,Name from user where id=:userinfo.getuserid() WITH SECURITY_ENFORCED].Name;
         document.case__c = caseId;
         document.Name__c = d.Name;
         Map<String, Schema.SObjectField> fields = ApexUtil.getObjectFieldsDescribe('DIA_Document__c');

         if(Schema.SobjectType.DIA_Document__c.iscreateable() && 
            fields.get('added_by__c').getDescribe().isAccessible() && 
            fields.get('case__c').getDescribe().isAccessible() &&
            fields.get('Name__c').getDescribe().isAccessible()){

            Database.SaveResult dsr = database.insert(document, false, AccessLevel.USER_MODE);
            if(dsr.isSuccess()){
               String modifiedFileName;
               if(caseRecord.Subject_Type__c == 'Applicant'){
                  modifiedFileName = 'A'; 
               }else if(caseRecord.Subject_Type__c == 'Contractor'){
                  modifiedFileName = 'A'; 
               }
               modifiedFileName = modifiedFileName + caseRecord.Contact__r.SSN__c+'Att00_'+d.Name;
               d.name=modifiedFileName;
               d.parentid=dsr.getid();
      
              controller.save();
              PageReference redirect = new PageReference('/apex/bicasedetail?id='+caseId+'&tab=Documents');
              redirect.setRedirect(true);
              return redirect;
            }else{
               return null;
            }
         }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to create Document'));
            return null;
         }
         
    }
  
   }