force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/DIA_Case__c.object-meta.xml
<CustomObject>
    <label>DIA Case</label>
    <nameField>
        <displayFormat>DIACase-{000000}</displayFormat>
        <label>DIA Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIACases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/DIA_Lead__c.object-meta.xml
<CustomObject>
    <label>DIA Lead</label>
    <nameField>
        <displayFormat>DIALead-{000000}</displayFormat>
        <label>DIA Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Lead__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIA_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipName>DIA_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject contact (SUBC)</fullName>
                <label>Subject Recontact (SUBC)</label>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_ROI_Report_Order__c/DIA_ROI_Report_Order__c.object-meta.xml
<CustomObject>
    <label>DIA ROI Report Order</label>
    <nameField>
        <displayFormat>DIAROIOrder-{0000000}</displayFormat>
        <label>DIA ROI Report Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA ROI Report Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_ROI_Report_Order__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>DIA Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipLabel>DIA ROI Report Orders</relationshipLabel>
    <relationshipName>DIA_ROI_Report_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIA_ROI_Report_Order__c/fields/ROI_Report_Order__c.field-meta.xml
<CustomField>
    <fullName>ROI_Report_Order__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ROI Report Order</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ROI_Report_Order__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case__c</referenceTo>
    <relationshipLabel>ROI Report Orders</relationshipLabel>
    <relationshipName>ROI_Report_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DIAOrderROIReportControllerTest.cls
@isTest
public class DIAOrderROIReportControllerTest {
    TestMethod static void DIAOrderROIReportController(){
        Account acc = new Account(name='ISN');
        insert acc;
        DIACaseWizardController wizardController = new DIACaseWizardController();
        //To create new subject
        wizardController.newSubject.First_Name__c = 'test';
        wizardController.newSubject.Last_Name__c = 'investigator';
        wizardController.newSubject.Phone__c = '8197277272';
        wizardController.newSubject.State__c = 'CA';
        wizardController.newSubject.Email__c = 'test.investigator@test.com';
        
        pagereference pref = wizardController.CreateNewSubjectAction();
        //To search for existing subject
        wizardController.subjectFirstNameSearchEntry = 'test';
        wizardController.subjectLastNameSearchEntry = 'investigator';
        wizardController.subjectEmailSearchEntry = 'test.investigator@test.com';
        wizardController.SearchSubjectsAction();
        //check if the subject is present in the system.
        system.assertEquals(1, wizardController.subjectsSearched.size());
        wizardController.subjectsSearched[0].isSelected = true;
        //create a case
        wizardController.CreateCaseAction();
        List<DIA_case__c> casesCreated = [Select Id from DIA_case__c];
        
        DIAOrderROIReportController oCtrl = new DIAOrderROIReportController();
        oCtrl.GenerateROIReport();
        oCtrl.GenerateNattachROIReport();
        oCtrl.caseId = casesCreated[0].id;
        DIA_ROI_Report_Order__c roiOrder = new DIA_ROI_Report_Order__c();
        roiOrder.case__c = casesCreated[0].id;
        
        roiOrder.ROI_Report_Order__c ='1,2,3';
        insert roiOrder;
        oCtrl.currentsequenceid =roiOrder.id; 
        oCtrl.GenerateROIDraft();
        octrl.GenerateImprovisedROIDraft();
        dia_lead__c ld = new dia_lead__c();
        ld.case__c = casesCreated[0].id;
        ld.Assigned_To__c = userinfo.getuserId();
        ld.LeadType__c = 'Employment (EMPL)';
        insert ld;
        
        //ROIReportController test starts...
        PageReference ROIReport2 = Page.BIROIReportV2;
        Test.setCurrentPage(ROIReport2);
        ROIReport2.getParameters().put('id',casesCreated[0].id);
        ROIReport2.getParameters().put('sequenceid',roiOrder.id);
        DIAROIReportControllerV2 roictrl = new DIAROIReportControllerV2 ();
        
        DIAOrderROIReportController oCtrl1 = new DIAOrderROIReportController();
        oCtrl1.GenerateROIReport();
        oCtrl1.GenerateNattachROIReport();
        oCtrl1.caseId = casesCreated[0].id;
        DIA_ROI_Report_Order__c roiOrder1 = new DIA_ROI_Report_Order__c();
        roiOrder1.case__c = casesCreated[0].id;
        
        roiOrder1.ROI_Report_Order__c ='1,2,3';
        insert roiOrder1; 
        oCtrl1.GenerateROIDraft();
        oCtrl1.GenerateImprovisedROIDraft();
    }
}