force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tier 5</fullName>
            </value>
            <value>
                <fullName>Tier 5 Reinvestigation</fullName>
            </value>
            <value>
                <fullName>Triggered Investigation</fullName>
            </value>
            <value>
                <fullName>Supplemental Investigation</fullName>
            </value>
            <value>
                <fullName>High Tier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Added_By__c.field-meta.xml
<CustomField>
    <fullName>Added_By__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Added By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ForesiteFileUploadPageController.cls
/** Handles the standard attachment upload flow for a PPF case. */
@SuppressWarnings('PMD.ApexDoc, PMD.ApexCRUDViolation, PMD.ApexXSSFromURLParam')
public without sharing class ForesiteFileUploadPageController {
    public string caseid;
    public case__c caseRecord {get;set;}
    public ApexPages.StandardController controller; // NOPMD - legacy structure retained to preserve behavior
    public ForesiteFileUploadPageController (ApexPages.StandardController controller) {
        this.controller = controller;
        String requestedCaseId = apexpages.currentpage().getparameters().get('caseid');
        caseId = String.isBlank(requestedCaseId)
            ? null
            : String.valueOf(Id.valueOf(requestedCaseId));
        List<Case__c> cases = [Select Subject_Type__c,Case_Number__c ,case_type__c, Contact__r.SSN__c from Case__c where Id=: caseId];
        if(!cases.isEMpty()){
           caseRecord = cases[0];
        }
    } 
    public PageReference saveAndRedirect() {
         Attachment d = (Attachment) controller.getRecord();
         Document__c document = new Document__c();
         document.added_by__c = [Select Id,Name from user where id=:userinfo.getuserid()].Name;
         document.case__c = caseId;
         document.Name__c = d.Name;
         insert document;
         String modifiedFileName;
         if(caseRecord.Subject_Type__c == 'Applicant'){
            modifiedFileName = 'A'; 
         }else if(caseRecord.Subject_Type__c == 'Contractor'){
            modifiedFileName = 'A'; 
         }
         modifiedFileName = modifiedFileName + caseRecord.Contact__r.SSN__c+'Att00_'+d.Name;
         d.name=modifiedFileName;
         d.parentid=document.id;

        controller.save();
        PageReference redirect = new PageReference('/apex/casedetail?id='+caseId+'&tab=Documents');
        redirect.setRedirect(true);
        return redirect;
    }
  
   }