force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/DIA_Case__c.object-meta.xml
<CustomObject>
    <label>DIA Case</label>
    <nameField>
        <displayFormat>DIACase-{000000}</displayFormat>
        <label>DIA Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DIA_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Is_ROI_Report_Generated__c.field-meta.xml
<CustomField>
    <fullName>Is_ROI_Report_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ROI Report Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Delivered canceled</fullName>
            </value>
            <value>
                <fullName>Delivered pending item(s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Subject_Type__c.field-meta.xml
<CustomField>
    <fullName>Subject_Type__c</fullName>
    <label>Subject Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Contact__c/DIA_Contact__c.object-meta.xml
<CustomObject>
    <label>DIA Contact</label>
    <nameField>
        <displayFormat>DIAContact-{000000}</displayFormat>
        <label>DIA Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Contact__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIA_Contact__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Document__c/DIA_Document__c.object-meta.xml
<CustomObject>
    <label>DIA Document</label>
    <nameField>
        <displayFormat>DIADoc-{000000}</displayFormat>
        <label>DIA Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Document__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/DIA_Lead__c.object-meta.xml
<CustomObject>
    <label>DIA Lead</label>
    <nameField>
        <displayFormat>DIALead-{000000}</displayFormat>
        <label>DIA Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Lead__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipName>DIA_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DIA_Contact__c</referenceTo>
    <relationshipName>DIA_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Assigned Not Accepted</fullName>
            </value>
            <value>
                <fullName>Investigator Rejected</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Applied For Waiver</fullName>
            </value>
            <value>
                <fullName>QA Rejected</fullName>
            </value>
            <value>
                <fullName>QA Review Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_ROI_Report_Order__c/DIA_ROI_Report_Order__c.object-meta.xml
<CustomObject>
    <label>DIA ROI Report Order</label>
    <nameField>
        <displayFormat>DIAROIOrder-{0000000}</displayFormat>
        <label>DIA ROI Report Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA ROI Report Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_ROI_Report_Order__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>DIA Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipLabel>DIA ROI Report Orders</relationshipLabel>
    <relationshipName>DIA_ROI_Report_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DIA_ROI_Report_Order__c/fields/ROI_Report_Order__c.field-meta.xml
<CustomField>
    <fullName>ROI_Report_Order__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ROI Report Order</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Added_By__c.field-meta.xml
<CustomField>
    <fullName>Added_By__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Added By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ROI_Report_Order__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case__c</referenceTo>
    <relationshipLabel>ROI Report Orders</relationshipLabel>
    <relationshipName>ROI_Report_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DIAOrderROIReportController.cls
public with sharing class DIAOrderROIReportController {
    public string caseId {get;set;}
    public DIA_Case__c caseRecord {get;set;}
    public List<LeadRecord> leadRecords {get;set;}
    public list<selectoption> orderOptions {get;set;}
    public string type{get;set;}
    public DIAOrderROIReportController(){
        caseId = apexpages.currentpage().getparameters().get('id');
        type= apexpages.currentpage().getparameters().get('type');
        orderOptions = new list<selectoption>();
        FetchCaseInformation();
        FetchLeadInformation();
        showroireport = false;
        showimprovisedroireport = false;
        
    }
    public void FetchCaseInformation(){
        List<string> caseFields = new List<string>();
        List<ApexUtil.Criteria> whereCriteria = new List<ApexUtil.Criteria>();
        caseFields = ApexUtil.FetchFields('DIA_Case__c');
        caseFields.add('contact__r.First_Name__c');
        caseFields.add('contact__r.Last_Name__c');
        caseFields.add('contact__r.Email__c');
        caseFields.add('contact__r.Address__c');
        caseFields.add('contact__r.City__c');
        caseFields.add('contact__r.State__c');
        caseFields.add('contact__r.Zip__c');
        caseFields.add('contact__r.SSN__c');
        String query = 'Select '+string.join(caseFields, ',') + ' From DIA_Case__c ';
        
        if(String.isNotBlank(caseId)){
            whereCriteria.add(new ApexUtil.Criteria('Id',caseId,'='));
        }
        
        String where_cond = ApexUtil.generateWhereQuery(whereCriteria); 
        if(!Test.isrunningTest()){
            query = query + ' WHERE '+where_cond+' WITH SECURITY_ENFORCED'; 
        }
        
        System.debug('query...'+query);
        list<DIA_Case__c> cases = database.query(query);
        if(!cases.isEmpty()){
            caseRecord = cases[0]; 
        }    
    }
    
    public void FetchLeadInformation(){
        orderOptions.add(new selectoption('','--None--'));
        leadRecords = new list<LeadRecord>();
        list<DIA_lead__c> leads = new List<DIA_lead__c> ();
        List<string> leadFields = new List<string>();
        List<ApexUtil.Criteria> whereCriteria = new List<ApexUtil.Criteria>();
        leadFields = ApexUtil.FetchFields('DIA_lead__c');  
        leadFields.add('contact__r.First_Name__c');    
        leadFields.add('contact__r.Last_Name__c');   
        String query = 'Select '+string.join(leadFields, ',') + ' From DIA_lead__c ';
        
        if(String.isNotBlank(string.valueof(caseId))){
            whereCriteria.add(new ApexUtil.Criteria('Case__c',caseId,'='));
        }
        whereCriteria.add(new ApexUtil.Criteria('Status__c','Cancelled','!='));
        String where_cond = ApexUtil.generateWhereQuery(whereCriteria);
        if(!Test.isrunningTest()){
			query = query + ' WHERE '+where_cond+ ' WITH SECURITY_ENFORCED ORDER BY Item_Number__c ASC '; 
        }
        
        leads = database.query(query);
        System.debug('leadquery...'+query);
        Integer i = 1;
        for(DIA_lead__c l: leads){
            leadRecords.add(new leadRecord(l,null));    
            orderOptions.add(new selectoption(string.valueof(i),string.valueof(i)));
            i++;
        }
    }
    
    public class LeadRecord{
        public DIA_lead__c lead{get;set;}
        public integer leadNumber {get;set;}
        public LeadRecord(DIA_lead__c l, integer  ln){
            this.lead = l;
           
            this.leadnumber = ln;
        }
    }
    public string roiOrderId {get;set;}
    public PageReference GenerateROIReport(){
        DIA_ROI_Report_Order__c roiOrder = new DIA_ROI_Report_Order__c();
        roiOrder.case__c = caseRecord.id;
        
        String order;
        //leadRecords.sort();
       map<double,DIA_lead__c> orderNLeadMap = new map<double,DIA_lead__c>();
       list<integer> leadNumbers = new list<integer>();
        for(LeadRecord lr: leadRecords){  
            if(lr.leadNumber != Null){
                System.debug('lr...'+lr.leadNumber);
                orderNLeadMap.put(lr.leadNumber,lr.lead);
                leadNumbers.add(lr.leadNumber);
            }    
        }
        
        
        leadNumbers.sort();
        System.debug('leadnumbers...'+leadnumbers);
        String leaditemnumbers;
        for(integer ln:leadNumbers){
            if(leaditemnumbers == Null){
                leaditemnumbers = String.valueof(orderNLeadMap.get(ln).item_number__c);     
                    } else{
                        leaditemnumbers = leaditemnumbers + ','+String.valueof(orderNLeadMap.get(ln).item_number__c);           
                    } 
        }
        System.debug('leaditemnumbers...'+leaditemnumbers);
        roiOrder.ROI_Report_Order__c = leaditemnumbers;

        Map<String, Schema.SObjectField> fields = ApexUtil.getObjectFieldsDescribe('DIA_ROI_Report_Order__c');

        if(Schema.SobjectType.DIA_ROI_Report_Order__c.iscreateable() && 
            fields.get('ROI_Report_Order__c').getDescribe().isAccessible() && 
            fields.get('case__c').getDescribe().isAccessible()){

            Database.SaveResult dsr = database.insert(roiOrder, false, AccessLevel.USER_MODE);
            if(dsr.isSuccess()){
                roiOrderId = dsr.getId();
                PageReference redirectPage = Page.BIROIReportV2;
                redirectPage.setRedirect(true);
                redirectPage.getParameters().put('id',caseRecord.id);
                redirectPage.getParameters().put('sequenceid',dsr.getId());
                return redirectPage;
            }else{
                return null;
            }
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to generate ROI Report Order'));
            return null;
        }
    }
    
    public PageReference GenerateNattachROIReport(){
     DIA_ROI_Report_Order__c roiOrder = new DIA_ROI_Report_Order__c();
        roiOrder.case__c = caseRecord.id;
        
        String order;
        //leadRecords.sort();
       map<double,DIA_lead__c> orderNLeadMap = new map<double,DIA_lead__c>();
       list<integer> leadNumbers = new list<integer>();
        for(LeadRecord lr: leadRecords){  
            if(lr.leadNumber != Null){
                System.debug('lr...'+lr.leadNumber);
                orderNLeadMap.put(lr.leadNumber,lr.lead);
                leadNumbers.add(lr.leadNumber);
            }    
        }
        
        
        leadNumbers.sort();
        System.debug('leadnumbers...'+leadnumbers);
        String leaditemnumbers;
        for(integer ln:leadNumbers){
            if(leaditemnumbers == Null){
                leaditemnumbers = String.valueof(orderNLeadMap.get(ln).item_number__c);     
                    } else{
                        leaditemnumbers = leaditemnumbers + ','+String.valueof(orderNLeadMap.get(ln).item_number__c);           
                    } 
        }
        System.debug('leaditemnumbers...'+leaditemnumbers);
        roiOrder.ROI_Report_Order__c = leaditemnumbers;

        Map<String, Schema.SObjectField> fields = ApexUtil.getObjectFieldsDescribe('DIA_ROI_Report_Order__c');

        if(Schema.SobjectType.DIA_ROI_Report_Order__c.iscreateable() && 
            fields.get('ROI_Report_Order__c').getDescribe().isAccessible() && 
            fields.get('case__c').getDescribe().isAccessible()){

            Database.SaveResult dsr = database.insert(roiOrder, false, AccessLevel.USER_MODE);
            if(dsr.isSuccess()){
                myFutureMethod(caseRecord.id,dsr.getId());
                PageReference redirectPage = Page.BICaseDetail;
                redirectPage.setRedirect(true);
                redirectPage.getParameters().put('id',caseRecord.id);
                return redirectPage;
            }else{
                return null;
            }
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to generate ROI Report Order'));
            return null;
        }
       /* Document__c doc = new Document__c();
        doc.Name__c = 'ROIReport';
        doc.case__c = caseRecord.id;
        doc.Added_By__c = UserInfo.getFirstName() + ' '+ UserInfo.getLastName();
        insert doc;
        
        string applicantType;
        string ssnFormatted;
        if(caseRecord.Subject_Type__c == 'Applicant'){
            applicantType = 'A';
        }
        if(caseRecord.Subject_Type__c == 'Contractor'){
            applicantType = 'C';
        }
        if(caseRecord.Contact__r.SSN__c != Null){
            ssnFormatted = caseRecord.Contact__r.SSN__c.replaceAll('-','');
        }
        PageReference pr= Page.BIROIReportV2;
        pr.getParameters().put('sequenceid',roiOrder.id);
        pr.getParameters().put('id',caseRecord.Id);
           
       
        Attachment att = new attachment();
        att.ParentId = doc.id;
        att.Name = applicantType + ssnFormatted + 'Rev00.pdf';
        if(!test.isRunningTest()){
            att.Body = pr.getContentAsPDF();    
        }else{
            att.body = blob.valueof('temp');
        }
        
        att.ContentType = 'application/pdf';
        insert att;*/
        
    }
    
    @future(callout=true)
    public static void myFutureMethod(string caseId, string sequenceId)
    {   
        DIA_Document__c doc = new DIA_Document__c();
        doc.Name__c = 'ROIReport';
        doc.case__c = caseId;
        doc.Added_By__c = UserInfo.getFirstName() + ' '+ UserInfo.getLastName();

        Map<String, Schema.SObjectField> fields = ApexUtil.getObjectFieldsDescribe('DIA_Document__c');
        if(Schema.SobjectType.DIA_Document__c.iscreateable() && 
                fields.get('Name__c').getDescribe().isAccessible() && 
                fields.get('case__c').getDescribe().isAccessible() &&
                fields.get('Added_By__c').getDescribe().isAccessible()){
                Database.SaveResult dsr = database.insert(doc, false, AccessLevel.USER_MODE);
                if(dsr.isSuccess()){
                    DIA_Case__c caseRecord = [select Subject_Type__c,Contact__r.SSN__c from DIA_Case__c where id=:caseId WITH SECURITY_ENFORCED limit 1 ];
                    string applicantType;
                    string ssnFormatted;
                    if(caseRecord.Subject_Type__c == 'Applicant'){
                        applicantType = 'A';
                    }
                    if(caseRecord.Subject_Type__c == 'Contractor'){
                        applicantType = 'C';
                    }
                    if(caseRecord.Contact__r.SSN__c != Null){
                        ssnFormatted = caseRecord.Contact__r.SSN__c.replaceAll('-','');
                    }
                    PageReference pr= Page.BIROIReportV2;
                    pr.getParameters().put('sequenceid',sequenceId);
                    pr.getParameters().put('id',caseId);
                    
                
                    Attachment att = new attachment();
                    att.ParentId = dsr.getId();
                    att.Name = applicantType + ssnFormatted + 'Rev00.pdf';
                    if(!test.isRunningTest()){
                        att.Body = pr.getContentAsPDF();    
                    }else{
                        att.body = blob.valueof('temp');
                    }
                    
                    att.ContentType = 'application/pdf';
                    Map<String, Schema.SObjectField> attFields = ApexUtil.getObjectFieldsDescribe('Attachment');
                    if(Schema.SobjectType.Attachment.iscreateable() && 
                        attFields.get('ParentId').getDescribe().isAccessible() && 
                        attFields.get('Name').getDescribe().isAccessible() &&
                        attFields.get('Body').getDescribe().isAccessible()){
                            Database.SaveResult dsra = database.insert(att, false, AccessLevel.USER_MODE);
                            
                            dia_case__c cs = [select id,Is_ROI_Report_Generated__c from dia_case__c where id =: caseId];
                            cs.Is_ROI_Report_Generated__c = true;
                            update cs;
                        }else{
                            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to create Attachment'));
                        }
                }
            }else{
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to create Document'));
                
            }
        
    }
    public string currentsequenceid {get;set;}
    public void GenerateROIDraft(){
         String order;    
         map<double,DIA_lead__c> orderNLeadMap = new map<double,DIA_lead__c>();
         list<integer> leadNumbers = new list<integer>();
          String leaditemnumbers;
        for(LeadRecord lr: leadRecords){  
           if(leaditemnumbers == Null){
               leaditemnumbers = String.valueof(lr.lead.item_number__c);
           }else{
               leaditemnumbers = leaditemnumbers+ ','+String.valueof(lr.lead.item_number__c);
           }
        }
        
        
       
        System.debug('leaditemnumbers...'+leaditemnumbers);
        if(currentsequenceid != Null){
            list<DIA_ROI_Report_Order__c> roiOrder = [Select Id, ROI_Report_Order__c, case__C from DIA_ROI_Report_Order__c WHERE Id=:currentsequenceid WITH SECURITY_ENFORCED];
            if(!roiOrder.isEmpty()){
                
                 roiOrder[0].ROI_Report_Order__c = leaditemnumbers;
                 Map<String, Schema.SObjectField> fields = ApexUtil.getObjectFieldsDescribe('DIA_ROI_Report_Order__c');

                if(Schema.SobjectType.DIA_ROI_Report_Order__c.isUpdateable() && 
                    fields.get('ROI_Report_Order__c').getDescribe().isAccessible()){

                    List<Database.SaveResult> dsr = database.update(roiOrder, false, AccessLevel.USER_MODE);
                }else{
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to update ROI Report Order'));
                }
            }
        }else{
            DIA_ROI_Report_Order__c roiOrder = new DIA_ROI_Report_Order__c();
            roiOrder.case__c = caseRecord.id;
            roiOrder.ROI_Report_Order__c = leaditemnumbers;
            Map<String, Schema.SObjectField> fields = ApexUtil.getObjectFieldsDescribe('DIA_ROI_Report_Order__c');

                if(Schema.SobjectType.DIA_ROI_Report_Order__c.iscreateable() && 
                    fields.get('ROI_Report_Order__c').getDescribe().isAccessible() && 
                    fields.get('case__c').getDescribe().isAccessible()){
                    Database.SaveResult dsr = database.insert(roiOrder, false, AccessLevel.USER_MODE);
                    if(dsr.isSuccess()){
                        currentsequenceid = dsr.getId();  
                    }
                }else{
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to update ROI Report Order'));
                }
        }
        showroireport = true;
        showimprovisedroireport = false;
    }
    
    public void GenerateImprovisedROIDraft(){
         String order;    
         map<double,DIA_lead__c> orderNLeadMap = new map<double,DIA_lead__c>();
         list<integer> leadNumbers = new list<integer>();
          String leaditemnumbers;
        for(LeadRecord lr: leadRecords){  
           if(leaditemnumbers == Null){
               leaditemnumbers = String.valueof(lr.lead.item_number__c);
           }else{
               leaditemnumbers = leaditemnumbers+ ','+String.valueof(lr.lead.item_number__c);
           }
        }
        
        
       
        System.debug('leaditemnumbers...'+leaditemnumbers);
        if(currentsequenceid != Null){
            list<DIA_ROI_Report_Order__c> roiOrder = [Select Id, ROI_Report_Order__c, case__C from DIA_ROI_Report_Order__c WHERE Id=:currentsequenceid WITH SECURITY_ENFORCED];
            if(!roiOrder.isEmpty()){
                
                 roiOrder[0].ROI_Report_Order__c = leaditemnumbers;
                 Map<String, Schema.SObjectField> fields = ApexUtil.getObjectFieldsDescribe('DIA_ROI_Report_Order__c');

                if(Schema.SobjectType.DIA_ROI_Report_Order__c.isUpdateable() && 
                    fields.get('ROI_Report_Order__c').getDescribe().isAccessible()){

                    List<Database.SaveResult> dsr = database.update(roiOrder, false, AccessLevel.USER_MODE);
                }else{
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to update ROI Report Order'));
                }
            }
        }else{
            DIA_ROI_Report_Order__c roiOrder = new DIA_ROI_Report_Order__c();
            roiOrder.case__c = caseRecord.id;
            roiOrder.ROI_Report_Order__c = leaditemnumbers;
            Map<String, Schema.SObjectField> fields = ApexUtil.getObjectFieldsDescribe('DIA_ROI_Report_Order__c');

                if(Schema.SobjectType.DIA_ROI_Report_Order__c.iscreateable() && 
                    fields.get('ROI_Report_Order__c').getDescribe().isAccessible() && 
                    fields.get('case__c').getDescribe().isAccessible()){
                    Database.SaveResult dsr = database.insert(roiOrder, false, AccessLevel.USER_MODE);
                    if(dsr.isSuccess()){
                        currentsequenceid = dsr.getId();  
                    }
                }else{
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to update ROI Report Order'));
                }
        }
        showimprovisedroireport = true;
        showroireport = false;
    }
    
    public boolean showroireport {get;set;}
    public boolean showimprovisedroireport {get;set;}
}