force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/DIA_Case__c.object-meta.xml
<CustomObject>
    <label>DIA Case</label>
    <nameField>
        <displayFormat>DIACase-{000000}</displayFormat>
        <label>DIA Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIACases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Message__c/DIA_Message__c.object-meta.xml
<CustomObject>
    <label>DIA Message</label>
    <nameField>
        <displayFormat>DIAMessage-{000000}</displayFormat>
        <label>DIA Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Message__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DIA Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipLabel>DIA Messages</relationshipLabel>
    <relationshipName>DIA_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Message__c/fields/From_User__c.field-meta.xml
<CustomField>
    <fullName>From_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIA_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Message__c/fields/To_User__c.field-meta.xml
<CustomField>
    <fullName>To_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIA_Messages1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Message__c/fields/UnRead__c.field-meta.xml
<CustomField>
    <fullName>UnRead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>UnRead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DIAMyMessagesControllerTest.cls
@isTest
public class DIAMyMessagesControllerTest {
testMethod private static void TestMyMessagesController(){
         list<user> currentUsers = [Select Id, User_Type__c,system_access__c,profile.name from User where contactid != Null or profile.name = 'System Administrator'];
        for(user u:currentUsers){
        u.User_Type__c = 'PMO';
        u.system_access__c = 'DIA';
        }
        update currentUsers;
        DIA_Case__c c = new DIA_Case__c();
        c.case_number__c = 'test';
        c.assigned_to__c = userinfo.getuserid();
        insert c;
        DIA_Message__c message = new DIA_Message__c();
        message.Message_Body__c = 'Test';
        message.subject__c = 'Test Subject';
        message.From_User__c = userinfo.getUserId();
        message.to_user__c = userinfo.getUserId();
        message.read__c =false;  
        message.unread__c =true; 
        message.case__c = c.id;  
        insert message;
        DIAMyMessagesController mymessagesCtrl = new DIAMyMessagesController();
        mymessagesCtrl.currentMessageId = message.id;
        mymessagesCtrl.FetchCurrentMessageAction();
        mymessagesCtrl.messageBody = 'Test';
        mymessagesCtrl.messageSubject = 'Test';
        mymessagesCtrl.selecteToAddressOption = 'All Program Members';
        mymessagesCtrl.SendMessage();
        mymessagesCtrl.RefreshAction();
        mymessagesCtrl.selecteToAddressOption = 'All Investigators';
        mymessagesCtrl.SendMessage();
        mymessagesCtrl.selecteToAddressOption = 'All PMOs';
        mymessagesCtrl.SendMessage();
        mymessagesCtrl.selecteToAddressOption = 'All CMOs';
        mymessagesCtrl.SendMessage();
        mymessagesCtrl.selecteToAddressOption = 'All QAs';
        mymessagesCtrl.SendMessage();
    }
}