force-app/main/default/objects/DHS_OTP__c/DHS_OTP__c.object-meta.xml
<CustomObject>
    <label>OTP</label>
    <nameField>
        <displayFormat>OPTNumber-{000000000}</displayFormat>
        <label>OTP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OTP</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_OTP__c/fields/DHS_User__c.field-meta.xml
<CustomField>
    <fullName>DHS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_OTP</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_OTP__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <formula>Now() &gt;  Expire_Time__c</formula>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DHS_OTP__c/fields/OTP__c.field-meta.xml
<CustomField>
    <fullName>OTP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>OTP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OTP__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generated</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DHSLoginFlow_Controller_Test.cls
@istest

/** Exercises the existing DHSLoginFlow_Controller_ behavior. */
@SuppressWarnings('PMD.AnnotationsNamingConventions, PMD.ApexUnitTestClassShouldHaveRunAs, PMD.LocalVariableNamingConventions')
public class DHSLoginFlow_Controller_Test {

    @IsTest static void getdata()

    {

        DHSLoginFlow_Controller L = New DHSLoginFlow_Controller();

        L.createOTPrecord();

       

        List<DHS_OTP__c> otpRecord = [select id,OTP__c,DHS_User__c,Status__c,Expired__c from DHS_OTP__c where DHS_User__c =: UserInfo.getUserId() AND  Status__c = 'Generated' AND Expired__c = false];

                      system.assertEquals(1,otpRecord.size(), 'Assertion failed in DHSLoginFlow_Controller_Test at source line 19');

       

        DHSLoginFlow_Controller L1 = New DHSLoginFlow_Controller();

        L1.ErrorCount = 0 ;

        L1.OTPrecId = otpRecord[0].Id;

        L1.EnteredOTPfromUser = otpRecord[0].OTP__c;

        L1.VerifyOTP();

        L1.EnteredOTPfromUser ='234567';

        L1.VerifyOTP();

        L1.EnteredOTPfromUser ='234567';

        L1.VerifyOTP();

        L1.EnteredOTPfromUser ='345678';

        L1.VerifyOTP();

    }

}