force-app/main/default/objects/Auto_Lead_Generation_Setting__c/Auto_Lead_Generation_Setting__c.object-meta.xml
<CustomObject>
    <label>Auto Lead Generation Setting</label>
    <nameField>
        <displayFormat>ALGS-{000000}</displayFormat>
        <label>Auto Lead Generation Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auto Lead Generation Setting</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Auto_Lead_Generation_Setting__c/fields/Auto_Lead_Generation_Template__c.field-meta.xml
<CustomField>
    <fullName>Auto_Lead_Generation_Template__c</fullName>
    <label>Auto Lead Generation Template</label>
    <referenceTo>Auto_Lead_Generation_Template__c</referenceTo>
    <relationshipLabel>Auto Lead Generation Setting</relationshipLabel>
    <relationshipName>Auto_Lead_Generation_Setting</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Auto_Lead_Generation_Setting__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Subject Interview</fullName>
            </value>
            <value>
                <fullName>General Record</fullName>
            </value>
            <value>
                <fullName>Subject Recontact</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Auto_Lead_Generation_Setting__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject Recontact (SUBC)</fullName>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Auto_Lead_Generation_Template__c/Auto_Lead_Generation_Template__c.object-meta.xml
<CustomObject>
    <label>Auto Lead Generation Template</label>
    <nameField>
        <displayFormat>ALGT-{000000}</displayFormat>
        <label>Auto Lead Generation Template Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auto Lead Generation Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DIALeadCreationSettingsControllerTest.cls
@isTest
public class DIALeadCreationSettingsControllerTest {
	testMethod private static void TestDIALeadCreationSettingsController(){ 
    	Auto_Lead_Generation_Template__c temp = new Auto_Lead_Generation_Template__c(Name__c='Test');
        insert temp;
        Auto_Lead_Generation_Setting__c setting = new Auto_Lead_Generation_Setting__c();
        setting.Auto_Lead_Generation_Template__c =temp.id;
        setting.Coverage_Type__c = 'Personal';
        setting.Item_number__c = 1;
        setting.Lead_Type__c = 'UnEmployment';
        insert setting;
        DIALeadCreationSettingsController ctrl = new DIALeadCreationSettingsController();
        ctrl.selectedTemplate = temp.id;
        ctrl.FetchSettingsOfTemplate();
        ctrl.CreateNewTemplate();
        ctrl.newTemplate.name__c = 'Test2';
        ctrl.Savetemplate();
        ctrl.addsetting();
        list<DIALeadCreationSettingsController.SettingRecord> settingRecords = ctrl.autoLeadGenerationSettings;
        
        integer i = 0;
        for(DIALeadCreationSettingsController.SettingRecord sr: settingRecords){
            Auto_Lead_Generation_Setting__c setting1 = sr.setting;
            setting1.Coverage_Type__c = 'Personal';
            setting1.Item_number__c = i;
            setting1.Lead_Type__c = 'UnEmployment';
            i++;
        }
        ctrl.SaveSettings();
        
        
    }
}