force-app/main/default/objects/DHS_Auto_Lead_Generation_Setting__c/fields/DHS_Auto_Lead_Generation_Template__c.field-meta.xml
<CustomField>
    <fullName>DHS_Auto_Lead_Generation_Template__c</fullName>
    <label>Auto Lead Generation Template</label>
    <referenceTo>DHS_Auto_Lead_Generation_Template__c</referenceTo>
    <relationshipLabel>Auto Lead Generation Setting</relationshipLabel>
    <relationshipName>DHS_Auto_Lead_Generation_Setting</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHS_Auto_Lead_Generation_Setting__c/fields/Item_number__c.field-meta.xml
<CustomField>
    <fullName>Item_number__c</fullName>
    <label>Item Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/DHS_Case__c.object-meta.xml
<CustomObject>
    <label>Case</label>
    <nameField>
        <displayFormat>Case-{000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Case__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>DHS_Contact_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Contact__c/DHS_Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Contact__c/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Investigator</fullName>
            </value>
            <value>
                <fullName>Subject</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/DHS_Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{000000}</displayFormat>
        <label>Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Lead__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Subject Interview</fullName>
            </value>
            <value>
                <fullName>General Record</fullName>
            </value>
            <value>
                <fullName>Subject Recontact</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>DHS_Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Assigned_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Case__c.field-meta.xml
<CustomField>
    <fullName>DHS_Case__c</fullName>
    <label>Case</label>
    <referenceTo>DHS_Case__c</referenceTo>
    <relationshipName>DHS_Case_Leads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/DHS_Contact__c.field-meta.xml
<CustomField>
    <fullName>DHS_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DHS_Contact__c</referenceTo>
    <relationshipName>DHS_Contact_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/Item_number__c.field-meta.xml
<CustomField>
    <fullName>Item_number__c</fullName>
    <label>Item number</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject Recontact (SUBC)</fullName>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Publicly Available Electronic Information (PAEI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DHS_Lead__c/recordTypes/Unemployment.recordType-meta.xml
<RecordType>
    <fullName>Unemployment</fullName>
    <active>true</active>
    <label>Unemployment</label>
</RecordType>

force-app/main/default/classes/DHSCaseDashboardControllerTest.cls
@IsTest
@SuppressWarnings('PMD.ApexAssertionsShouldIncludeMessage,PMD.ApexUnitTestClassShouldHaveAsserts,PMD.ApexUnitTestClassShouldHaveRunAs,PMD.NcssCount,PMD.UnusedLocalVariable')
public class DHSCaseDashboardControllerTest {
      @TestSetup static void setup() {
         DHS_Contact__c con = new DHS_Contact__c();
         con.First_Name__c = 'Test';
         con.Last_Name__c = 'Name';
         con.Email__c  = 'test@test.com';
         con.Contact_Type__c = 'Subject';
         con.SSN__c = '123-12-1123';
         insert con;
          
         DHS_Case__c caseTemp = new DHS_Case__c();
         caseTemp.DHS_Contact__c = con.id;
         caseTemp.DHS_Assigned_To__c = userinfo.getuserId();
         insert caseTemp;
         DHS_Lead__c lead = new DHS_Lead__c();
         lead.DHS_Case__c = caseTemp.id;
         //Lead.DHS_Assigned_To__c = userinfo.getuserid();
         lead.Coverage_Type__c = 'Subject Interview';
         lead.LeadType__c = 'Subject Interview (ESI/TESI)';
         insert lead;
     }
    @IsTest private static void testMethod1(){ 
        DHS_Case__c c = [select id from DHS_Case__c limit 1];
          DHSCaseDashboardController dashboardCtrl = new DHSCaseDashboardController();   
        dashboardCtrl.subjectFirstNameSearchEntry = 'test';
        dashboardCtrl.subjectLastNameSearchEntry = 'investigator';
        dashboardCtrl.caseStatusSearchEntry = 'Completed';
        dashboardCtrl.fromSubmissionDateSearchEntry = system.today();
        dashboardCtrl.toSubmissionDateSearchEntry = system.today();
        dashboardCtrl.caseNumberSearchEntry = 'asdasd';
        dashboardCtrl.caseManifestSearchEntry = 'asdasd';
        dashboardCtrl.caseTypeSearchEntry = 'asdasd';
        dashboardCtrl.SearchAction();
        system.assertEquals(1,dashboardCtrl.casesSearched.size());
        dashboardCtrl.casesSearched[0].isSelected = true;
        //dashboardCtrl.casesSearched[1].isSelected = true;
        dashboardCtrl.selectedUserIdForAssignment = userinfo.getUserId();
        dashboardCtrl.AssignCasesAction();
        Integer totalNumberOfQACases = DHSCaseDashboardController.totalNumberOfQACases();
        Integer totalNumberLeadsForCase = DHSCaseDashboardController.totalNumberLeadsForCase(c.id);
        PageReference caseDashboardPage = Page.DHSCasedashboard;
        Test.setCurrentPage(caseDashboardPage);
        caseDashboardPage.getParameters().put('showUnAssigned','true'); 
        DHSCaseDashboardController dashboardCtrl2 = new DHSCaseDashboardController();   
        caseDashboardPage.getParameters().put('subjectFirstNameSearchEntry','test'); 
        caseDashboardPage.getParameters().put('subjectLastNameSearchEntry','test'); 
        caseDashboardPage.getParameters().put('caseNumberSearchEntry','test'); 
        caseDashboardPage.getParameters().put('caseManifestSearchEntry','test'); 
        caseDashboardPage.getParameters().put('caseAssigneeearchEntry','test'); 
        caseDashboardPage.getParameters().put('caseTypeSearchEntry','test'); 
        caseDashboardPage.getParameters().put('fromSubmissionDateSearchEntry',string.valueof(system.today())); 
        caseDashboardPage.getParameters().put('toSubmissionDateSearchEntry',string.valueof(system.today())); 
        DHSCaseDashboardController dashboardCtrl3 = new DHSCaseDashboardController(); 
        caseDashboardPage.getParameters().clear();
        caseDashboardPage.getParameters().put('showQACases','true');  
        caseDashboardPage.getParameters().put('subjectFirstNameSearchEntry','test'); 
        caseDashboardPage.getParameters().put('subjectLastNameSearchEntry','test'); 
        caseDashboardPage.getParameters().put('caseNumberSearchEntry','test'); 
        caseDashboardPage.getParameters().put('caseManifestSearchEntry','test'); 
        caseDashboardPage.getParameters().put('caseAssigneeearchEntry','test'); 
        caseDashboardPage.getParameters().put('caseTypeSearchEntry','test'); 
        caseDashboardPage.getParameters().put('fromSubmissionDateSearchEntry',string.valueof(system.today())); 
        caseDashboardPage.getParameters().put('toSubmissionDateSearchEntry',string.valueof(system.today())); 
        DHSCaseDashboardController dashboardCtrl4 = new DHSCaseDashboardController();   
           
    }
     @IsTest private static void testAutoCreateLeads(){
        DHS_Auto_Lead_Generation_Template__c temp = new DHS_Auto_Lead_Generation_Template__c(Name__c='Test');
        insert temp;
        DHS_Auto_Lead_Generation_Setting__c setting = new DHS_Auto_Lead_Generation_Setting__c();
        setting.DHS_Auto_Lead_Generation_Template__c =temp.id;
        setting.Coverage_Type__c = 'Personal';
        setting.Item_number__c = 1;
        setting.Lead_Type__c = 'UnEmployment';
        insert setting;
        PageReference casedetailpage = Page.DHSCasedetail;
        Test.setCurrentPage(casedetailpage);
        DHS_Case__c c = new DHS_Case__c();
        insert c;
       
    }
}