force-app/main/default/objects/Customer_Order_Upload_Log__c/Customer_Order_Upload_Log__c.object-meta.xml
<CustomObject>
    <label>Customer Order Upload Log</label>
    <nameField>
        <displayFormat>COUL-{0000000}</displayFormat>
        <label>Customer Order Upload Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Order Upload Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Order_Upload_Log__c/fields/DIA_Customer_Order__c.field-meta.xml
<CustomField>
    <fullName>DIA_Customer_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DIA Customer Order</label>
    <referenceTo>DIA_Customer_Order__c</referenceTo>
    <relationshipLabel>Customer Order Upload Logs</relationshipLabel>
    <relationshipName>Customer_Order_Upload_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/DIA_Case__c.object-meta.xml
<CustomObject>
    <label>DIA Case</label>
    <nameField>
        <displayFormat>DIACase-{000000}</displayFormat>
        <label>DIA Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/fields/Case_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Completed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DIA_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Current_Task__c.field-meta.xml
<CustomField>
    <fullName>Current_Task__c</fullName>
    <label>Current Task</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initiated State</fullName>
            </value>
            <value>
                <fullName>Validate Transmission</fullName>
            </value>
            <value>
                <fullName>Scoping</fullName>
            </value>
            <value>
                <fullName>Investigations</fullName>
            </value>
            <value>
                <fullName>Investigations Review</fullName>
            </value>
            <value>
                <fullName>QA and Review</fullName>
            </value>
            <value>
                <fullName>QA Review Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>DIA_Customer_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Delivered canceled</fullName>
            </value>
            <value>
                <fullName>Delivered pending item(s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Contact__c/DIA_Contact__c.object-meta.xml
<CustomObject>
    <label>DIA Contact</label>
    <nameField>
        <displayFormat>DIAContact-{000000}</displayFormat>
        <label>DIA Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Contact__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DIA_Customer_Order__c/DIA_Customer_Order__c.object-meta.xml
<CustomObject>
    <label>DIA Customer Order</label>
    <nameField>
        <displayFormat>DIAOrder-{000000}</displayFormat>
        <label>DIA Customer Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Customer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Customer_Order__c/fields/ACD_Date__c.field-meta.xml
<CustomField>
    <fullName>ACD_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ACD Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIA_Customer_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Uploaded</fullName>
                <default>true</default>
                <label>Uploaded</label>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Document__c/DIA_Document__c.object-meta.xml
<CustomObject>
    <label>DIA Document</label>
    <nameField>
        <displayFormat>DIADoc-{000000}</displayFormat>
        <label>DIA Document Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Document__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>DIA_Case__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UpdateACDDateController.cls
global class UpdateACDDateController {
    public List<OrderRecord> customerOrders {get;set;}
    public List<OrderRecord> UploadedcustomerOrders {get;set;}
    public List<OrderRecord> executedCustomerOrders {get;set;}
    public Map<Id,List<DIA_Case__c>> executedCustomerOrdersandCasesMap {get;set;}
    public Map<Id,DIA_Customer_order__c> executedCustomerOrdersMap {get;set;}
    global string subjectFirstNameSearchEntry {get;set;}
    global string subjectLastNameSearchEntry {get;set;}
    global string subjectSSNSearchEntry {get;set;}
    global List<deliverableWrapper> deliverables {get;set;}
    @RemoteAction
    global static void CreateOrderNDocuments(list<string> contentversionIds){
        system.debug('contentversionIds....'+contentversionIds);
        list<contentversion> contentVersions = [select id,ContentDocumentId from contentversion WHERE ID IN:contentversionIds];
        list<string> contentDocumentIds = new list<string>();
        for(contentversion cv: contentVersions){
        	contentDocumentIds.add(cv.ContentDocumentId);    
        }
        Customer_Order_Upload_Log__c log = new Customer_Order_Upload_Log__c();
        list<ContentDocumentLink> cdlsToCreate = new list<ContentDocumentLink>();
        DIA_Customer_Order__c co = new DIA_Customer_Order__c ();
        co.status__c = 'Uploaded';
        try{
        	insert co; 
            log.DIA_Customer_Order__c  = co.id;
        }catch(Exception ex){
        	log.Error_Message__c = ex.getmessage();        
        }
        insert log;
        for(string contentDocumentId : contentDocumentIds){
        	ContentDocumentLink cdl = new ContentDocumentLink();
			cdl.ContentDocumentId = contentDocumentId;
            cdl.LinkedEntityId = co.id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            cdlsToCreate.add(cdl);
        }
        if(!cdlsToCreate.isEmpty()){
        	insert cdlsToCreate;    
        }
      
        ExecuteCustomerOrdersBatch ctrl = new ExecuteCustomerOrdersBatch(co.id,log.id);
        database.executebatch(ctrl);
    }
    
    public void GetCustomerOrders(){
    	 uploadedcustomerOrders = new List<OrderRecord> ();
        executedCustomerOrders = new List<OrderRecord> ();
        UploadedcustomerOrders = FetchOrderInformation('Uploaded'); 
        executedCustomerOrders = FetchOrderInformation('Executed');
        list<string> executedCustomerOrderIds = new list<string>();
        for(OrderRecord ord: executedCustomerOrders){
            executedCustomerOrderIds.add(ord.order.id);    
        }     
        executedCustomerOrdersandCasesMap = new Map<Id,List<DIA_Case__c>>();
        executedCustomerOrdersMap = new Map<Id,DIA_Customer_order__c> ([Select Id, Status__c,ACD_Date__c from DIA_Customer_order__c where id in:executedCustomerOrderIds order by createddate desc]);
        List<DIA_Case__c> cases = FetchCasesofCustomerOrder(executedCustomerOrderIds);
        for(DIA_Case__c c: cases){
            if(!executedCustomerOrdersandCasesMap.containsKey(c.order__c)){
                executedCustomerOrdersandCasesMap.put(c.order__c, new list<DIA_Case__c> {c});
            }else{
                executedCustomerOrdersandCasesMap.get(c.order__c).add(c);
            }
        }
        for(OrderRecord ord: executedCustomerOrders){
            if(!executedCustomerOrdersandCasesMap.containsKey(ord.order.id)){
                executedCustomerOrdersandCasesMap.put(ord.order.id,new list<dia_case__c>{});  
            }    
        }      
    }
    public UpdateACDDateController(){
       getDeliverables();
       GetCustomerOrders();
    }
      global void getDeliverables(){
        deliverables = New List<deliverableWrapper>();
        List<ApexUtil.Criteria> whereCriteria = new List<ApexUtil.Criteria>();
        List<string> caseFields = new List<string>();
        caseFields = ApexUtil.FetchFields('DIA_Case__c');
        caseFields.add('CreatedBy.Name');
		caseFields.add('Contact__r.Last_Name__c');
        String query = 'Select '+string.join(caseFields, ',') + ',(select id,Name__c from documents__r) From DIA_Case__c ';
        String where_cond;
        if(String.isNotBlank(string.valueof(subjectFirstNameSearchEntry))){
            whereCriteria.add(new ApexUtil.Criteria('Contact__r.First_Name__c', '%'+String.escapeSingleQuotes(subjectFirstNameSearchEntry)+'%', 'LIKE'));
        }
        if(String.isNotBlank(string.valueof(subjectLastNameSearchEntry))){
            whereCriteria.add(new ApexUtil.Criteria('Contact__r.Last_Name__c', '%'+String.escapeSingleQuotes(subjectLastNameSearchEntry)+'%', 'LIKE'));
        }
        if(String.isNotBlank(string.valueof(subjectSSNSearchEntry))){
            whereCriteria.add(new ApexUtil.Criteria('Contact__r.SSN__c', '%'+subjectSSNSearchEntry+'%', 'LIKE'));
        }
        whereCriteria.add(new ApexUtil.Criteria('Current_Task__c', 'QA Review Completed', '='));
        where_cond = ApexUtil.generateWhereQuery(whereCriteria); 
        System.debug('whereCriteria...'+whereCriteria);
        System.debug('where_cond...'+where_cond);
        query = query + ' WHERE '+where_cond+' Order by CreatedDate Desc';
        list<DIA_Case__c> cases = database.query(query);
          system.debug(cases);
        Map<string,string> docNcaseMap = new Map<string,string>();
        for(DIA_Case__c cse : cases){
            if(cse.documents__r.size() > 0){
                for(dia_document__c doc : cse.documents__r){
                    if(doc.Name__c == 'ROIReport'){
                        system.debug(doc.Name__c);
                        docNcaseMap.put(cse.Id,doc.Id);
                    }
				}
			}
		}
        Map<string,string> docNatt = New Map<string,string>();
        List<attachment> att = [select id,parentId from attachment where parentId IN: docNcaseMap.values()];
        for(attachment a : att){
            docNatt.put(a.parentId,a.Id);
		}
        for(DIA_Case__c cse : cases){
            deliverableWrapper del = New deliverableWrapper();
            del.caseNumber = cse.Case_Number__c;
            del.createdBy = cse.CreatedBy.Name;
            del.createdDate = cse.createddate;
            del.documentId = docNatt.get(docNcaseMap.get(cse.Id));
            del.caseId = cse.Id;
            del.completedDate = cse.Case_Completed_Date__c;
            del.dueDate = cse.Case_Due_Date__c;
            del.lastName = cse.Contact__r.Last_Name__c;
            deliverables.add(del);
        }
        if(deliverables.size() > 0){
            for(deliverableWrapper dele : deliverables){
                system.debug(dele.caseNumber);
                system.debug(dele.createdDate);
                system.debug(dele.createdBy);
                system.debug(dele.documentId);
            }
        }
	}
        global class deliverableWrapper{
            global string caseId {get;set;}
            global string caseNumber {get;set;}
            global datetime createdDate {get;set;}
            global string createdBy {get;set;}
            global string documentId {get;set;}
            global date completedDate {get;set;}
            global date dueDate {get;set;}
            global string lastName {get;set;}
        }
    public list<DIA_Case__c> FetchCasesofCustomerOrder(list<string> orderids){
        List<string> caseFields = new List<string>();
        List<ApexUtil.Criteria> whereCriteria = new List<ApexUtil.Criteria>();
        caseFields = ApexUtil.FetchFields('DIA_Case__c');
        String query = 'Select '+string.join(caseFields, ',') + ' From DIA_Case__c ';
        String where_cond;
        //whereCriteria.add(new ApexUtil.Criteria('Order__c', orderids, 'IN:'));
        //where_cond = ApexUtil.generateWhereQuery(whereCriteria);    
        System.debug('where_cond...'+where_cond);
        query = query + ' WHERE Order__c in:orderids'; 
        System.debug('query...'+query);
        list<DIA_Case__c> cases = database.query(query);
        return cases;
    }
    public class OrderRecord{
        public string attachmentId{get;set;}   
        public DIA_Customer_order__c order{get;set;}
        public string logMessage{get;set;}
        public string logAttachmentId{get;set;}
        public OrderRecord(string attachmentId, DIA_Customer_order__c order, string logMessage,string logAttachmentId){
            this.order = order;    
            this.attachmentId = attachmentId;
            this.logMessage = logMessage;
            this.logAttachmentId = logAttachmentId;
        }
    }
    
    public void SaveOrderAction(){
    	list<DIA_Customer_order__c> ordersToUpdate = new list<DIA_Customer_order__c>();
        for(OrderRecord oRecord: executedCustomerOrders){
            if(oRecord.order.acd_date__c != Null){
            	ordersToUpdate.add(oRecord.order);    
            }    
        }
        if(!ordersToUpdate.isEmpty()){
            update ordersToUpdate;
            GetCustomerOrders();
        }
    }
    
    public List<OrderRecord> FetchOrderInformation(string status){
        List<OrderRecord> customerOrders = new List<OrderRecord> ();
        List<string> orderFields = new List<string>();
        List<ApexUtil.Criteria> whereCriteria = new List<ApexUtil.Criteria>();
        orderFields = ApexUtil.FetchFields('DIA_Customer_order__c'); 
        orderFields.add('owner.name');
        String query = 'Select '+string.join(orderFields, ',') + ' From DIA_Customer_order__c ';
        //whereCriteria.add(new ApexUtil.Criteria('Status__c',status, '=')); 
        String where_cond = ApexUtil.generateWhereQuery(whereCriteria); 
        if(String.isNotblank(where_cond)){
            query = query + ' WHERE '+where_cond ;     
        }else{
            query = query+' Order by createddate desc';         
        }
        System.debug('query...'+query);
        list<DIA_Customer_order__c> orders = database.query(query);
        List<string> orderIds = new List<string>();
        for(DIA_Customer_order__c doc: orders){
            orderIds.add(doc.id);
        }
        list< Customer_Order_Upload_Log__c  > logs= new list< Customer_Order_Upload_Log__c >();
        logs = [select id, Error_Message__c ,DIA_Customer_Order__c from Customer_Order_Upload_Log__c where DIA_Customer_Order__c IN:orderIds  ];
        map<string, Customer_Order_Upload_Log__c> orderNlogMap = new map<string,Customer_Order_Upload_Log__c>();
        map<string, string> logNattachmentMap = new map<string,string>();
        list<string> logIds =new list<string>();
        for(Customer_Order_Upload_Log__c log: logs){
        	orderNlogMap.put(log.DIA_Customer_Order__c,log);
            logIds.add(log.id);
        }
        list<attachment> atts = [select id, parentid,name from attachment where parentid in:logIds ];
        for(attachment att: atts){
        	logNattachmentMap.put(att.parentid,att.id);    
        }
        
        List<ContentDocumentLink> documentsAttached = new List<ContentDocumentLink>();
        if(!orderIds.isEmpty())
        documentsAttached = [Select id, ContentDocumentId, ContentDocument.title, LinkedEntityId from ContentDocumentLink WHERE LinkedEntityId IN: orderids and ContentDocument.title='OrderData.csv'];
        Map<String,String> orderNattachmentMap = new Map<String,String>();
        for(ContentDocumentLink cdl: documentsAttached){
            orderNattachmentMap.put(cdl.LinkedEntityId, cdl.ContentDocumentId);    
        }
        
        for(DIA_Customer_order__c doc: orders){
            if(orderNlogMap.get(doc.id) == Null){
            	customerOrders.add(new OrderRecord(orderNattachmentMap.get(doc.id),doc,null,null));      
            }else if(orderNlogMap.get(doc.id).error_message__c != Null){
            	customerOrders.add(new OrderRecord(orderNattachmentMap.get(doc.id),doc,orderNlogMap.get(doc.id).error_message__c,null));      	    
            }else if(logNattachmentMap.get(orderNlogMap.get(doc.id).id) != Null){
            	customerOrders.add(new OrderRecord(orderNattachmentMap.get(doc.id),doc,null,logNattachmentMap.get(orderNlogMap.get(doc.id).id)));      	    
            }
            
        }
        
        return customerOrders;
    }
	
}