force-app/main/default/objects/Contact__c/Contact__c.object-meta.xml
<CustomObject>
    <label>Contact</label>
    <nameField>
        <displayFormat>Contact-{000000}</displayFormat>
        <label>Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/DIA_Case__c.object-meta.xml
<CustomObject>
    <label>DIA Case</label>
    <nameField>
        <displayFormat>DIACase-{000000}</displayFormat>
        <label>DIA Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Case__c/fields/Case_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Completed_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Case_Queue_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Queue_Status__c</fullName>
    <label>Case Queue Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Closure_Type__c.field-meta.xml
<CustomField>
    <fullName>Closure_Type__c</fullName>
    <label>Closure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed T5</fullName>
            </value>
            <value>
                <fullName>Cancelled T5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>DIA_Contact__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/ISP_requested_Extension__c.field-meta.xml
<CustomField>
    <fullName>ISP_requested_Extension__c</fullName>
    <label>ISP requested Extension</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/ISP_requested_Waiver__c.field-meta.xml
<CustomField>
    <fullName>ISP_requested_Waiver__c</fullName>
    <label>ISP requested Waiver</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Case__c/fields/SF_86_Certification_Date__c.field-meta.xml
<CustomField>
    <fullName>SF_86_Certification_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SF-86 Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DIA_Contact__c/DIA_Contact__c.object-meta.xml
<CustomObject>
    <label>DIA Contact</label>
    <nameField>
        <displayFormat>DIAContact-{000000}</displayFormat>
        <label>DIA Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Contact__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>SSN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BIManifestReportsControllerTest.cls
@isTest
public class BIManifestReportsControllerTest {
	TestMethod static void BIManifestReportsTest(){
        account acc = New account(name = 'ISN');
        insert acc;
        
        string fileName = 'Manifest from ';
        ContentVersion objCV = new ContentVersion();
        objCV.Title = fileName;
            objCV.PathOnClient = fileName+'.CSV';
        objCV.VersionData = blob.valueOf('{}');
            insert objCV;
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: objCV.Id].ContentDocumentId;
            cdl.LinkedEntityId = [Select Id from Account Where Name='ISN'].id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            insert cdl;
        
        dia_contact__c diacon = new dia_contact__c();
        diacon.First_Name__c = 'Test';
        diacon.Last_Name__c = 'User';
        diacon.SSN__c = '12312-3123';
        insert diacon;
        
        dia_case__c cs = New dia_case__c();
        cs.Contact__c = diacon.Id;
        cs.case_number__c = 'Test12345';
        cs.Case_Completed_Date__c = system.today();
        cs.Coverage_Period_Begin_Date__c = system.today();
        cs.Closure_Type__c = 'Completed T5';
        cs.ISP_requested_Extension__c = 'No';
        cs.ISP_requested_Waiver__c = 'No';
        cs.SF_86_Certification_Date__c = system.today();
        cs.Case_Queue_Status__c = 'Completed';
        insert cs;
        Test.startTest();
        BIManifestReportsController sp = New BIManifestReportsController();
        sp.fromDate = system.today();
        sp.toDate = system.today();
        sp.formatDate(system.today());
        sp.createContentVersion('Waiver Request','Test');
        sp.generateCustomDateRangeManifest();
        sp.regenerateManifest();
        sp.generateCustomDateRangeOppSummary();
        sp.generateCustomDateRangeExtensionRequest();
        sp.generateCustomDateRangeWaiverRequest();
        Test.stopTest();
    }
}