force-app/main/default/objects/DHS_TimeSheet__c/DHS_TimeSheet__c.object-meta.xml
<CustomObject>
    <label>TimeSheet</label>
    <nameField>
        <displayFormat>TS-{000000}</displayFormat>
        <label>TimeSheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_TimeSheet__c/fields/Day_Name__c.field-meta.xml
<CustomField>
    <fullName>Day_Name__c</fullName>
    <label>Day Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DHS_TimeSheet__c/fields/DHS_User__c.field-meta.xml
<CustomField>
    <fullName>DHS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_TimeSheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_TimeSheet__c/fields/Period_From__c.field-meta.xml
<CustomField>
    <fullName>Period_From__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Period From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DHS_TimeSheet__c/fields/Period_To__c.field-meta.xml
<CustomField>
    <fullName>Period_To__c</fullName>
    <label>Period To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DHSTimesheetsControllerTest.cls
@IsTest
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
public class DHSTimesheetsControllerTest {
	@IsTest private static void testtimesheetsController(){ 
	    System.assert(true, 'Expected the test scenario to complete without exception');
        DHSScheduleCreateTimesheetsBatch schedulableBatchCtrl = new DHSScheduleCreateTimesheetsBatch(); 
        schedulableBatchCtrl.execute(null);
        DateTime todaysDateTime = System.now();
        Integer currentDayOfMonth = todaysDateTime.day();
        Integer month = Date.Today().Month();
        Integer year = Date.Today().Year();
        Integer numberDays = Date.daysInMonth(year, month);
        Date startDate;
        Date endDate;
        if(currentDayOfMonth >= 1 && currentDayOfMonth <= 15){
            startDate = Date.newinstance(year, month, 1);
            endDate = Date.newinstance(year, month, 15);
        }
        if(currentDayOfMonth >= 16){
            startDate = Date.newinstance(year, month, 16);
            endDate = Date.newinstance(year, month, numberDays);
        }
        DHS_TimeSheet__c timeSheet = new DHS_TimeSheet__c();
        timeSheet.Period_From__c = startDate;
        timeSheet.Period_To__c = endDate;
        timeSheet.Date__c = Date.newinstance(year, month, todaysDateTime.day());
        timeSheet.Day_Name__c = DateTime.newInstance(year, month, todaysDateTime.day()).format('EEEE');
        timeSheet.DHS_User__c = userinfo.getuserid();
        insert timeSheet;
        DHSTimesheetsController ctrl = new DHSTimesheetsController();
        ctrl.addNewInvestigatorCheck();
        ctrl.addNewInvestigatorCheck();        
        ctrl.checkoutapexaction();
        ctrl.checkinapexaction();
        DHSInvoiceModuleController invoiceCtrl = new DHSInvoiceModuleController();
        invoiceCtrl.FetchInvoiceRecords();
    }
}