force-app/main/default/objects/BI_Pricing__mdt/BI_Pricing__mdt.object-meta.xml
<CustomObject>
    <label>BI Pricing</label>
    <pluralLabel>BI Pricings</pluralLabel>
</CustomObject>

force-app/main/default/objects/BI_Pricing__mdt/fields/Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Contact_Method__c</fullName>
    <label>Contact Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Pricing__mdt/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Pricing__mdt/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <label>Lead Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BI_Pricing__mdt/fields/Unable_to_Complete__c.field-meta.xml
<CustomField>
    <fullName>Unable_to_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unable to Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/DIA_Lead__c.object-meta.xml
<CustomObject>
    <label>DIA Lead</label>
    <nameField>
        <displayFormat>DIALead-{000000}</displayFormat>
        <label>DIA Lead Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Leads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Lead__c/fields/Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Contact_Method__c</fullName>
    <label>Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Person (Record Provider)</fullName>
            </value>
            <value>
                <fullName>In-Person (directly by investigator)</fullName>
            </value>
            <value>
                <fullName>Telephone/Fax</fullName>
            </value>
            <value>
                <fullName>Approved Internet Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Record</fullName>
            </value>
            <value>
                <fullName>Subject Interview</fullName>
            </value>
            <value>
                <fullName>General Record</fullName>
            </value>
            <value>
                <fullName>Subject Recontact</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Last_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Status_Change__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Last Status Change</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject contact (SUBC)</fullName>
                <label>Subject Recontact (SUBC)</label>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Personal_Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Personal_Contact_Method__c</fullName>
    <label>Personal Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>By Telephone/Fax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Lead__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Assigned Not Accepted</fullName>
            </value>
            <value>
                <fullName>Investigator Rejected</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Applied For Waiver</fullName>
            </value>
            <value>
                <fullName>QA Rejected</fullName>
            </value>
            <value>
                <fullName>QA Review Completed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DIA_Lead_Status_History__c/DIA_Lead_Status_History__c.object-meta.xml
<CustomObject>
    <label>DIA Lead Status History</label>
    <nameField>
        <displayFormat>DIALSH-{0000000}</displayFormat>
        <label>DIA Lead Status History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DIA Lead Status Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DIA_Lead_Status_History__c/fields/Completed_By__c.field-meta.xml
<CustomField>
    <fullName>Completed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Completed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIA_Lead_Status_Histories2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Lead_Status_History__c/fields/Initiated_By__c.field-meta.xml
<CustomField>
    <fullName>Initiated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DIA_Lead_Status_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DIA_Lead_Status_History__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>DIA Lead</label>
    <referenceTo>DIA_Lead__c</referenceTo>
    <relationshipLabel>DIA Lead Status Histories</relationshipLabel>
    <relationshipName>DIA_Lead_Status_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Contact_Method__c</fullName>
    <label>Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Person (Record Provider)</fullName>
            </value>
            <value>
                <fullName>In-Person (directly by investigator)</fullName>
            </value>
            <value>
                <fullName>Approved Internet Site</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Coverage_Type__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Type__c</fullName>
    <label>Coverage Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadType__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Subject Interview</fullName>
            </value>
            <value>
                <fullName>General Record</fullName>
            </value>
            <value>
                <fullName>Subject Recontact</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject contact (SUBC)</fullName>
                <label>Subject Recontact (SUBC)</label>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Publicly Available Electronic Information (PAEI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Personal_Contact_Method__c.field-meta.xml
<CustomField>
    <fullName>Personal_Contact_Method__c</fullName>
    <label>Personal Contact Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Telephone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>By Telephone/Fax</fullName>
                <isActive>false</isActive>
                <label>By Telephone/Fax</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DIALeadTriggerHandler.cls
Public with sharing Class DIALeadTriggerHandler {
    public static void UpdatePricingOnLead(List<DIA_Lead__c> newLeads, Map<Id,DIA_Lead__c> oldLeadsMap){
    	List<BI_Pricing__mdt> biPricingMatrix = new List<BI_Pricing__mdt>();
     	biPricingMatrix = [select id, Lead_Type__c, Coverage_Type__c,Contact_Method__c ,Unable_to_Complete__c ,Price__c
                           FROM BI_Pricing__mdt];
        map<string,list<BI_Pricing__mdt>> leadTypeNpricingMatrix = new map<string,list<BI_Pricing__mdt>>();
        for(BI_Pricing__mdt bp: biPricingMatrix ){
            if(!leadTypeNpricingMatrix.containsKey(bp.Lead_Type__c)){
                leadTypeNpricingMatrix.put(bp.lead_type__c,new list<BI_Pricing__mdt>{bp});	    
            }else{
            	list<BI_Pricing__mdt> temp = leadTypeNpricingMatrix.get(bp.lead_type__c);
                temp.add(bp);
                leadTypeNpricingMatrix.put(bp.lead_type__c,temp);	    
            }   
        }
        for(DIA_Lead__c diaLead: newLeads){
            if(diaLead.status__c == 'Completed' && oldLeadsMap.get(dialead.id).status__c != 'Completed'){
                list<BI_Pricing__mdt> biPricings = new list<BI_Pricing__mdt>();
                biPricings = leadTypeNpricingMatrix.get(diaLead.leadtype__c);
                System.debug('biPricings...'+biPricings);
                if(biPricings != Null){
                    for(BI_Pricing__mdt bp:biPricings ){
                        if(diaLead.coverage_type__c == bp.coverage_type__c){
                            System.debug('bp...'+bp);
                            if(bp.contact_method__c != Null && bp.contact_method__c == dialead.personal_contact_method__c){
                                diaLead.price__c = bp.price__c;	
                                System.debug('inside this..');
                            }
                            if(bp.contact_method__c == Null){
                                diaLead.price__c = bp.price__c;    
                            }
                        }    
                    }
                }
            }  
            System.debug('diaLead.price__c...'+diaLead.price__c);
        }
    }
    public static void LeadAuditMethod(List<DIA_Lead__c> leadOldIds , List<DIA_Lead__c> LeadNewIds){
        List< DIA_Lead_Status_History__c > LSHList = New List< DIA_Lead_Status_History__c >();

        try
        {
             lisT<string> newLeadIds = new list<String>();
             For(DIA_Lead__c LN : LeadNewIds){
                 newLeadIds.add(ln.id);
             }
            list<DIA_Lead_Status_History__c> statusHistories = new list<DIA_Lead_Status_History__c>();
            statusHistories = [Select Id,Completed_By__c,lead__c FROM DIA_Lead_Status_History__c WHERE lead__c=:newLeadIds order by createddate desc];
            map<string,list<DIA_Lead_Status_History__c>> leadNstatushistorymap = new map<string,list<DIA_Lead_Status_History__c>>();
            for(DIA_Lead_Status_History__c temp: statusHistories){
                if(!leadNstatushistorymap.containsKey(temp.lead__c)){
                    leadNstatushistorymap.put((string)temp.lead__c,new list<DIA_Lead_Status_History__c>{temp});
                }else{
                    list<DIA_Lead_Status_History__c> temp2= leadNstatushistorymap.get(temp.lead__c);
                    temp2.add(temp);
                    leadNstatushistorymap.put((string)temp.lead__c,temp2);
                }
            }
                        
            For(DIA_Lead__c LO : leadOldIds)
            {
                For(DIA_Lead__c LN : LeadNewIds)
                {
                    System.debug('---LO.Last_Status_Change__c---'+LO.Last_Status_Change__c);
                    System.debug('---LN.Last_Status_Change__c---'+LN.Last_Status_Change__c);

                    IF((LO.Id == LN.Id) && (LO.Last_Status_Change__c != LN.Last_Status_Change__c))
                    {
                        list<DIA_Lead_Status_History__c> temp = new list<DIA_Lead_Status_History__c>();
                        if(leadNstatushistorymap.containsKey(ln.id)){
                            temp = leadNstatushistorymap.get(ln.id);
                        }
                        DIA_Lead_Status_History__c CSHVal = New DIA_Lead_Status_History__c();
                        if(!temp.isEmpty()){
                            CSHVal.initiated_By__c = temp[0].Completed_By__c;    
                        }else{
                            CSHVal.initiated_By__c = ln.createdbyid;
                        }
                        CSHVal.Completed_By__c = userinfo.getuserid();
                        CSHVal.Lead__C = LO.Id;
                        CSHVal.Status_Name__c = LO.Status__C;
                        CSHVal.Status_Start_Time__c = LO.Last_Status_Change__c;
                        CSHVal.Status_End_Time__c = LN.Last_Status_Change__c;
                        Long dt1Long = LO.Last_Status_Change__c.getTime();
                        Long dt2Long = LN.Last_Status_Change__c.getTime();
                        Long milliseconds = dt2Long - dt1Long;
                        Long seconds = milliseconds / 1000;
                        Long minutes = seconds / 60;
                        Long hours = minutes / 60;
                        Long days = hours / 24;
                        Long Subhours = (minutes - (days * 24 * 60)) / 60 ;
                        Long Submin = ((minutes - (days * 24 * 60)) - (Subhours * 60)) ;
                        CSHVal.Status_Duration__c = days + ' Days /  ' + Subhours + ' Hrs /  ' + Submin + ' Mins ';
                        LSHList.add(CSHVal);
                    }
                }
            }

            if(!LSHList.isEmpty()){
                Map<String, Schema.SObjectField> fields = ApexUtil.getObjectFieldsDescribe('DIA_Lead_Status_History__c');

                if(Schema.SobjectType.DIA_Lead_Status_History__c.iscreateable() && 
                    fields.get('initiated_By__c').getDescribe().isAccessible() && 
                    fields.get('Completed_By__c').getDescribe().isAccessible() &&
                    fields.get('Lead__C').getDescribe().isAccessible() &&
                    fields.get('Status_Name__c').getDescribe().isAccessible() &&
                    fields.get('Status_Start_Time__c').getDescribe().isAccessible() && 
                    fields.get('Status_End_Time__c').getDescribe().isAccessible()
                    ){

                    List<Database.SaveResult> dsr = database.insert(LSHList, false, AccessLevel.USER_MODE);
                }else{
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient access to create Lead Status History'));
                }
            }
        } Catch(Exception e){
        
        }       
    }
}