force-app/main/default/objects/Customer_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Uploaded</fullName>
                <default>true</default>
                <label>Uploaded</label>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject contact (SUBC)</fullName>
                <label>Subject Recontact (SUBC)</label>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Publicly Available Electronic Information (PAEI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OnBoarding__c/OnBoarding__c.object-meta.xml
<CustomObject>
    <label>OnBoarding</label>
    <nameField>
        <displayFormat>user-{000000}</displayFormat>
        <label>OnBoarding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OnBoarding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OnBoarding__c/fields/Candidate_type__c.field-meta.xml
<CustomField>
    <fullName>Candidate_type__c</fullName>
    <label>Candidate type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>SCA</fullName>
            </value>
            <value>
                <fullName>Non-SCA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OnBoarding__c/fields/User_Created__c.field-meta.xml
<CustomField>
    <fullName>User_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/IntelHeaderControllerTest.cls
@isTest
public class IntelHeaderControllerTest {
	testMethod private static void TestMisc(){
        IntelHeaderController ctrl = new IntelHeaderController();
        user currentUser = [Select Id, User_Type__c from User where Id=:userinfo.getuserid()];
        currentUser.User_Type__c = 'CMO';
        update currentUser;
        IntelHeaderController ctrl2 = new IntelHeaderController();
        currentUser = [Select Id, User_Type__c from User where Id=:userinfo.getuserid()];
        currentUser.User_Type__c = 'QA';
        update currentUser;
        IntelHeaderController ctrl3 = new IntelHeaderController();
        currentUser = [Select Id, User_Type__c from User where Id=:userinfo.getuserid()];
        currentUser.User_Type__c = 'INV';
        update currentUser;
        IntelHeaderController ctrl5 = new IntelHeaderController();
        currentUser = [Select Id, User_Type__c from User where Id=:userinfo.getuserid()];
        currentUser.User_Type__c = 'PMO';
        update currentUser;
        IntelHeaderController.updateLogoutTime();
        IntelHeaderController.updateIdleTime(10);
        IntelHeaderController ctrl4 = new IntelHeaderController();
        customer_order__c co = new customer_order__c(status__c = 'Uploaded'); insert co;
        customer_order__c co1 = new customer_order__c(status__c = 'Executed'); insert co1;        
        CustomerInterfaceController ciCtrl = new CustomerInterfaceController();
        
        onboarding__c onboardingUser = new onboarding__c();
        onboardingUser.First_Name__c = 'test';
        onboardingUser.Last_Name__c = 'investigator';
        onboardingUser.Email__c = 'testinvestigator@test.com';
        onboardingUser.Candidate_type__c = 'SCA';
        onboardingUser.User_Created__c = false;
        insert onboardingUser;
        
         Account acc = new Account(Name='ISN');
        insert acc;
        CreateUserFromOnboardingBatch CreateUserFromOnboardingBatchctrl = new CreateUserFromOnboardingBatch(onboardingUser.id);
        database.executeBatch(CreateUserFromOnboardingBatchctrl);
         PageReference IntelProfilePage = Page.IntelProfilePage;
        Test.setCurrentPage(IntelProfilePage);
        IntelProfilePage.getParameters().put('id',userinfo.getUserId());
        IntelProfilePageController ipc = new IntelProfilePageController();
        currentUser.Out_of_office__c = 'Vacation';
        ipc.updatefieldfisibility();
        
        ContentVersion content=new ContentVersion(); 
        content.Title='2022-02-11-12_46_39S_12313123123'; 
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        //content.LinkedEntityId=sPayoff.id;
        content.origin = 'H';
        insert content;
        
        //List<Schema.FieldSetMember> temp = ApexUtil.readFieldSet('OnboardingUser','OnboardingUser__c');
        Map<String, Id> temp2 =  ApexUtil.buildMapOfRecordTypes('Lead__c');
        Map<String, Schema.SObjectType> globalDescMap=Schema.getGlobalDescribe();
        Schema.SObjectType targetType=globalDescMap.get('Lead__c');
        sObject sObj=targetType.newSObject();
        list<String> temp24 = apexutil.getPickListValues(sObj,'LeadType__c');
        //list<string> temp3 = apexutil.getFieldSetFields('OnboardingUser','OnboardingUser__c');
        Map<object,object> temp5 = apexutil.getSObjectFieldTypes('Lead__c');
        List<string> userFields = ApexUtil.FetchFields('User');
        List<String> userFilters = new List<String>();
        userFilters.add('id =: currentUserId');
        String userQuery = ApexUtil.queryBuilder('User', userFields, userFilters);
        String onboardingQuery = ApexUtil.queryBuilder('Onboarding__c', 'OnboardingUser', new list<string>{});
    }
}