force-app/main/default/objects/DHS_Message__c/DHS_Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <displayFormat>Message-{000000}</displayFormat>
        <label>Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Message__c/fields/DHS_From_User__c.field-meta.xml
<CustomField>
    <fullName>DHS_From_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_From_User_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Message__c/fields/DHS_To_User__c.field-meta.xml
<CustomField>
    <fullName>DHS_To_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Messages1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Message__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/DHS_Message__c/fields/Read__c.field-meta.xml
<CustomField>
    <fullName>Read__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DHSOtherMessagesControllerTest.cls
@isTest
/** Exercises the existing DHSOtherMessagesController behavior. */
@SuppressWarnings('PMD.AnnotationsNamingConventions, PMD.ApexUnitTestClassShouldHaveAsserts, PMD.ApexUnitTestClassShouldHaveRunAs, PMD.MethodNamingConventions')
public class DHSOtherMessagesControllerTest{
    @IsTest private static void TestOtherMessagesController(){
        User pmoUser = PPFDHSTestUserFactory.createPmoUser();
        System.runAs(pmoUser) {
        DHS_Message__c message = new DHS_Message__c();
        message.Message_Body__c = 'Test';
        message.Subject__c = 'Test Subject';
        message.DHS_From_User__c = userinfo.getUserId();
        message.DHS_To_User__c = userinfo.getUserId();
        message.Read__c =false;  
        message.UnRead__c =true;   
        insert message;
        DHSOtherMessagesController ctrl = new DHSOtherMessagesController();
        ctrl.selectedTypeofMessage = 'DHS_All';
        ctrl.fetchmessages();
        System.assertEquals(1, ctrl.allIncomingMessages.size(), 'Assertion failed in DHSOtherMessagesControllerTest at source line 19');
        System.assertEquals(1, ctrl.allOutgoingMessages.size(), 'Assertion failed in DHSOtherMessagesControllerTest at source line 20');

        ctrl.selectedFromUserId = UserInfo.getUserId();
        ctrl.selectedToUserId = UserInfo.getUserId();
        ctrl.selectedTypeofMessage = 'Incoming';
        ctrl.fetchmessages();
        ctrl.selectedTypeofMessage = 'Sent Items';
        ctrl.fetchmessages();
        System.assertNotEquals(null, ctrl.allOutgoingMessages, 'Assertion failed in DHSOtherMessagesControllerTest at source line 28');
        }
   }
}