force-app/main/default/objects/DHS_Message__c/DHS_Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <displayFormat>Message-{000000}</displayFormat>
        <label>Message Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHS_Message__c/fields/DHS_From_User__c.field-meta.xml
<CustomField>
    <fullName>DHS_From_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_From_User_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Message__c/fields/DHS_To_User__c.field-meta.xml
<CustomField>
    <fullName>DHS_To_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>DHS_Messages1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHS_Message__c/fields/Message_Body__c.field-meta.xml
<CustomField>
    <fullName>Message_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DHSMessageTriggerTest.cls
@IsTest
/** Exercises the existing DHSMessageTrigger behavior. */
@SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
private class DHSMessageTriggerTest {
    @IsTest
    static void removesOfficeMarkupOnInsertAndUpdate() {
        DHS_Message__c message = new DHS_Message__c(
            Message_Body__c = '<o:p>body</o:p>',
            Subject__c = 'Trigger test',
            DHS_From_User__c = UserInfo.getUserId(),
            DHS_To_User__c = UserInfo.getUserId()
        );
        insert message;
        message = [
            SELECT Message_Body__c FROM DHS_Message__c WHERE Id = :message.Id
        ];
        System.assertEquals('body', message.Message_Body__c, 'Assertion failed in DHSMessageTriggerTest at source line 17');
        message.Message_Body__c = '<o:p>updated</o:p>';
        update message;
        System.assertEquals('updated', [
            SELECT Message_Body__c FROM DHS_Message__c WHERE Id = :message.Id
        ].Message_Body__c, 'Assertion failed in DHSMessageTriggerTest at source line 20');
    }
}