force-app/main/default/objects/Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <label>LeadType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subject Interview (ESI/TESI)</fullName>
            </value>
            <value>
                <fullName>General (GENL)</fullName>
            </value>
            <value>
                <fullName>Employment (EMPL)</fullName>
            </value>
            <value>
                <fullName>Medical (MEDI)</fullName>
            </value>
            <value>
                <fullName>Residence (RESI)</fullName>
            </value>
            <value>
                <fullName>Education (EDUC)</fullName>
            </value>
            <value>
                <fullName>Former Spouse (FMSP)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Subject contact (SUBC)</fullName>
                <label>Subject Recontact (SUBC)</label>
            </value>
            <value>
                <fullName>Financial (FINL)</fullName>
            </value>
            <value>
                <fullName>Public records (PUBR)</fullName>
            </value>
            <value>
                <fullName>Law Enforcement (LAWE)</fullName>
            </value>
            <value>
                <fullName>References (REFE)</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Publicly Available Electronic Information (PAEI)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OnBoarding__c/OnBoarding__c.object-meta.xml
<CustomObject>
    <label>OnBoarding</label>
    <nameField>
        <displayFormat>user-{000000}</displayFormat>
        <label>OnBoarding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OnBoarding</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ApexUtilTest.cls
@isTest
public class ApexUtilTest {
    TestMethod static void method1(){
        Map<String, Id> temp2 =  ApexUtil.buildMapOfRecordTypes('Lead__c');
        Map<String, Schema.SObjectType> globalDescMap=Schema.getGlobalDescribe();
        Schema.SObjectType targetType=globalDescMap.get('Lead__c');
        sObject sObj=targetType.newSObject();
        list<String> temp24 = apexutil.getPickListValues(sObj,'LeadType__c');
        //list<string> temp3 = apexutil.getFieldSetFields('OnboardingUser','OnboardingUser__c');
        Map<object,object> temp5 = apexutil.getSObjectFieldTypes('Lead__c');
        List<string> userFields = ApexUtil.FetchFields('User');
        List<String> userFilters = new List<String>();
        userFilters.add('id =: currentUserId');
        String userQuery = ApexUtil.queryBuilder('User', userFields, userFilters);
        String onboardingQuery = ApexUtil.queryBuilder('Onboarding__c', 'OnboardingUser', new list<string>{});
        ApexUtil.runningInASandbox();
        ApexUtil.getObjectFieldsDescribe('User');
        ApexUtil.dt(system.today());
		ApexUtil.dt(system.today(),true);
    }
    
}